using System;

namespace Microsoft.Exchange.Management.FederationProvisioning
{
	internal enum DomainError
	{
		InvalidPartner = 1001,
		InvalidPartnerCert,
		PartnerNotAuthorized,
		MemberNotAuthorized,
		InvalidManagementCertificate,
		MemberNotAuthenticated,
		InvalidDomainName = 2001,
		BlockedDomainName,
		InvalidDomainConfigId,
		DomainNotReserved,
		DomainUnavailable,
		DomainPendingChanges,
		DomainSuspended,
		DomainPendingConfiguration,
		NotPermittedForDomain,
		InvalidProgramId,
		ProofOfOwnershipNotValid,
		PasswordChangeRequiredForDomain,
		CanNotReleaseNamespace,
		DomainNotFederated,
		MemberNameInvalid = 3001,
		MemberNameBlocked,
		MemberNameUnavailable,
		MemberNameBlank,
		MemberNameIncludesInvalidChars,
		MemberNameIncludesDots,
		MemberNameInUse,
		ManagedMemberExists,
		ManagedMemberNotExists,
		UnmanagedMemberExists,
		UnmanagedMemberNotExists,
		MaxMembershipLimit,
		PasswordBlank,
		PasswordTooShort,
		PasswordTooLong,
		PasswordIncludesMemberName,
		PasswordIncludesInvalidChars,
		PasswordInvalid,
		InvalidNetId,
		InvalidOffer,
		InvalidAppId = 4001,
		InvalidAppIdAdminKey,
		MaxAppIdsReached,
		MaxUriReached,
		InvalidUri,
		InternalError = 9001,
		InvalidParameter,
		PassportError,
		ExchangeError,
		SubscriptionServicesError,
		TestForcedError,
		ServiceDown,
		NYI = 10001
	}
}
