using System;

namespace Microsoft.Exchange.Server.Storage.PhysicalAccess
{
	public enum TableClass
	{
		Unknown,
		Other = 0,
		MSysObjects = 0,
		MSysObjids = 0,
		Temp,
		TableFunction,
		LazyIndex,
		Message,
		Attachment,
		Folder,
		PseudoIndexMaintenance,
		Events,
		PseudoIndexControl,
		PseudoIndexDefinition,
		DeliveredTo,
		ReceiveFolder,
		ReceiveFolder2,
		SearchQueue,
		Tombstone,
		Watermarks,
		ExtendedPropertyNameMapping,
		Globals,
		MailboxIdentity,
		Mailbox,
		ReplidGuidMap,
		TimedEvents,
		PerUser,
		InferenceLog,
		UpgradeHistory,
		UserInfo,
		ApplyOperatorSuite,
		ColumnSuite,
		ColumnSuite2,
		CommonDataRowSuite,
		ConnectionSuiteHelper,
		CountOperatorSuite,
		DeleteOperatorSuite,
		InsertOperatorSuite,
		InsertOperatorSuite2,
		InsertOperatorSuite3,
		JoinOperatorSuite,
		JoinOperatorSuite2,
		OrdinalPositionOperatorSuite,
		OrdinalPositionOperatorSuite2,
		PreReadOperatorSuite,
		DataRowSuite,
		ReaderSuite,
		ReaderSuite2,
		SearchCriteriaSuite,
		SortOperatorSuite,
		TableOperatorSuite,
		TableOperatorSuite2,
		TableOperatorSuite3,
		TableOperatorSuite4,
		CategorizedTableOperatorSuiteHeader,
		CategorizedTableOperatorSuiteLeaf,
		CategorizedTableOperatorSuiteMessage,
		UpdateOperatorSuite,
		IndexAndOperatorSuite2,
		IndexAndOperatorSuite3,
		IndexOrOperatorSuite2,
		IndexOrOperatorSuite3,
		IndexNotOperatorSuite2,
		IndexNotOperatorSuite3,
		SqlConnectionSuite,
		JetColumnSuite,
		Partitioned,
		JetTableSuite,
		DistinctOperatorSuite,
		MaxValue
	}
}
