using System;

namespace System.Deployment.Internal.Isolation.Manifest
{
	internal enum CMS_ASSEMBLY_REFERENCE_FLAG
	{
		CMS_ASSEMBLY_REFERENCE_FLAG_OPTIONAL = 1,
		CMS_ASSEMBLY_REFERENCE_FLAG_VISIBLE,
		CMS_ASSEMBLY_REFERENCE_FLAG_FOLLOW = 4,
		CMS_ASSEMBLY_REFERENCE_FLAG_IS_PLATFORM = 8,
		CMS_ASSEMBLY_REFERENCE_FLAG_CULTURE_WILDCARDED = 16,
		CMS_ASSEMBLY_REFERENCE_FLAG_PROCESSOR_ARCHITECTURE_WILDCARDED = 32,
		CMS_ASSEMBLY_REFERENCE_FLAG_PREREQUISITE = 128
	}
}
