using System;

namespace System.Deployment.Internal.Isolation.Manifest
{
	internal enum CMS_FILE_HASH_ALGORITHM
	{
		CMS_FILE_HASH_ALGORITHM_SHA1 = 1,
		CMS_FILE_HASH_ALGORITHM_SHA256,
		CMS_FILE_HASH_ALGORITHM_SHA384,
		CMS_FILE_HASH_ALGORITHM_SHA512,
		CMS_FILE_HASH_ALGORITHM_MD5,
		CMS_FILE_HASH_ALGORITHM_MD4,
		CMS_FILE_HASH_ALGORITHM_MD2
	}
}
