using System;

namespace System.Deployment.Internal.Isolation.Manifest
{
	internal enum CMSSECTIONID
	{
		CMSSECTIONID_FILE_SECTION = 1,
		CMSSECTIONID_CATEGORY_INSTANCE_SECTION,
		CMSSECTIONID_COM_REDIRECTION_SECTION,
		CMSSECTIONID_PROGID_REDIRECTION_SECTION,
		CMSSECTIONID_CLR_SURROGATE_SECTION,
		CMSSECTIONID_ASSEMBLY_REFERENCE_SECTION,
		CMSSECTIONID_WINDOW_CLASS_SECTION = 8,
		CMSSECTIONID_STRING_SECTION,
		CMSSECTIONID_ENTRYPOINT_SECTION,
		CMSSECTIONID_PERMISSION_SET_SECTION,
		CMSSECTIONENTRYID_METADATA,
		CMSSECTIONID_ASSEMBLY_REQUEST_SECTION,
		CMSSECTIONID_REGISTRY_KEY_SECTION = 16,
		CMSSECTIONID_DIRECTORY_SECTION,
		CMSSECTIONID_FILE_ASSOCIATION_SECTION,
		CMSSECTIONID_COMPATIBLE_FRAMEWORKS_SECTION,
		CMSSECTIONID_EVENT_SECTION = 101,
		CMSSECTIONID_EVENT_MAP_SECTION,
		CMSSECTIONID_EVENT_TAG_SECTION,
		CMSSECTIONID_COUNTERSET_SECTION = 110,
		CMSSECTIONID_COUNTER_SECTION
	}
}
