using System;
using System.CodeDom.Compiler;
using System.Xml.Serialization;

namespace Microsoft.Exchange.EDiscovery.Export.EwsProxy
{
	[GeneratedCode("wsdl", "4.0.30319.17627")]
	[XmlType(Namespace = "http://schemas.microsoft.com/exchange/services/2006/types")]
	[Serializable]
	public enum UnindexedFieldURIType
	{
		[XmlEnum("folder:FolderId")]
		folderFolderId,
		[XmlEnum("folder:ParentFolderId")]
		folderParentFolderId,
		[XmlEnum("folder:DisplayName")]
		folderDisplayName,
		[XmlEnum("folder:UnreadCount")]
		folderUnreadCount,
		[XmlEnum("folder:TotalCount")]
		folderTotalCount,
		[XmlEnum("folder:ChildFolderCount")]
		folderChildFolderCount,
		[XmlEnum("folder:FolderClass")]
		folderFolderClass,
		[XmlEnum("folder:SearchParameters")]
		folderSearchParameters,
		[XmlEnum("folder:ManagedFolderInformation")]
		folderManagedFolderInformation,
		[XmlEnum("folder:PermissionSet")]
		folderPermissionSet,
		[XmlEnum("folder:EffectiveRights")]
		folderEffectiveRights,
		[XmlEnum("folder:SharingEffectiveRights")]
		folderSharingEffectiveRights,
		[XmlEnum("folder:DistinguishedFolderId")]
		folderDistinguishedFolderId,
		[XmlEnum("folder:PolicyTag")]
		folderPolicyTag,
		[XmlEnum("folder:ArchiveTag")]
		folderArchiveTag,
		[XmlEnum("item:ItemId")]
		itemItemId,
		[XmlEnum("item:ParentFolderId")]
		itemParentFolderId,
		[XmlEnum("item:ItemClass")]
		itemItemClass,
		[XmlEnum("item:MimeContent")]
		itemMimeContent,
		[XmlEnum("item:Attachments")]
		itemAttachments,
		[XmlEnum("item:Subject")]
		itemSubject,
		[XmlEnum("item:DateTimeReceived")]
		itemDateTimeReceived,
		[XmlEnum("item:Size")]
		itemSize,
		[XmlEnum("item:Categories")]
		itemCategories,
		[XmlEnum("item:HasAttachments")]
		itemHasAttachments,
		[XmlEnum("item:Importance")]
		itemImportance,
		[XmlEnum("item:InReplyTo")]
		itemInReplyTo,
		[XmlEnum("item:InternetMessageHeaders")]
		itemInternetMessageHeaders,
		[XmlEnum("item:IsAssociated")]
		itemIsAssociated,
		[XmlEnum("item:IsDraft")]
		itemIsDraft,
		[XmlEnum("item:IsFromMe")]
		itemIsFromMe,
		[XmlEnum("item:IsResend")]
		itemIsResend,
		[XmlEnum("item:IsSubmitted")]
		itemIsSubmitted,
		[XmlEnum("item:IsUnmodified")]
		itemIsUnmodified,
		[XmlEnum("item:DateTimeSent")]
		itemDateTimeSent,
		[XmlEnum("item:DateTimeCreated")]
		itemDateTimeCreated,
		[XmlEnum("item:Body")]
		itemBody,
		[XmlEnum("item:ResponseObjects")]
		itemResponseObjects,
		[XmlEnum("item:Sensitivity")]
		itemSensitivity,
		[XmlEnum("item:ReminderDueBy")]
		itemReminderDueBy,
		[XmlEnum("item:ReminderIsSet")]
		itemReminderIsSet,
		[XmlEnum("item:ReminderNextTime")]
		itemReminderNextTime,
		[XmlEnum("item:ReminderMinutesBeforeStart")]
		itemReminderMinutesBeforeStart,
		[XmlEnum("item:DisplayTo")]
		itemDisplayTo,
		[XmlEnum("item:DisplayCc")]
		itemDisplayCc,
		[XmlEnum("item:Culture")]
		itemCulture,
		[XmlEnum("item:EffectiveRights")]
		itemEffectiveRights,
		[XmlEnum("item:LastModifiedName")]
		itemLastModifiedName,
		[XmlEnum("item:LastModifiedTime")]
		itemLastModifiedTime,
		[XmlEnum("item:ConversationId")]
		itemConversationId,
		[XmlEnum("item:UniqueBody")]
		itemUniqueBody,
		[XmlEnum("item:Flag")]
		itemFlag,
		[XmlEnum("item:StoreEntryId")]
		itemStoreEntryId,
		[XmlEnum("item:InstanceKey")]
		itemInstanceKey,
		[XmlEnum("item:NormalizedBody")]
		itemNormalizedBody,
		[XmlEnum("item:EntityExtractionResult")]
		itemEntityExtractionResult,
		[XmlEnum("item:PolicyTag")]
		itemPolicyTag,
		[XmlEnum("item:ArchiveTag")]
		itemArchiveTag,
		[XmlEnum("item:RetentionDate")]
		itemRetentionDate,
		[XmlEnum("item:Preview")]
		itemPreview,
		[XmlEnum("item:PredictedActionReasons")]
		itemPredictedActionReasons,
		[XmlEnum("item:IsClutter")]
		itemIsClutter,
		[XmlEnum("item:RightsManagementLicenseData")]
		itemRightsManagementLicenseData,
		[XmlEnum("item:BlockStatus")]
		itemBlockStatus,
		[XmlEnum("item:HasBlockedImages")]
		itemHasBlockedImages,
		[XmlEnum("item:WebClientReadFormQueryString")]
		itemWebClientReadFormQueryString,
		[XmlEnum("item:WebClientEditFormQueryString")]
		itemWebClientEditFormQueryString,
		[XmlEnum("item:TextBody")]
		itemTextBody,
		[XmlEnum("item:IconIndex")]
		itemIconIndex,
		[XmlEnum("item:MimeContentUTF8")]
		itemMimeContentUTF8,
		[XmlEnum("message:ConversationIndex")]
		messageConversationIndex,
		[XmlEnum("message:ConversationTopic")]
		messageConversationTopic,
		[XmlEnum("message:InternetMessageId")]
		messageInternetMessageId,
		[XmlEnum("message:IsRead")]
		messageIsRead,
		[XmlEnum("message:IsResponseRequested")]
		messageIsResponseRequested,
		[XmlEnum("message:IsReadReceiptRequested")]
		messageIsReadReceiptRequested,
		[XmlEnum("message:IsDeliveryReceiptRequested")]
		messageIsDeliveryReceiptRequested,
		[XmlEnum("message:ReceivedBy")]
		messageReceivedBy,
		[XmlEnum("message:ReceivedRepresenting")]
		messageReceivedRepresenting,
		[XmlEnum("message:References")]
		messageReferences,
		[XmlEnum("message:ReplyTo")]
		messageReplyTo,
		[XmlEnum("message:From")]
		messageFrom,
		[XmlEnum("message:Sender")]
		messageSender,
		[XmlEnum("message:ToRecipients")]
		messageToRecipients,
		[XmlEnum("message:CcRecipients")]
		messageCcRecipients,
		[XmlEnum("message:BccRecipients")]
		messageBccRecipients,
		[XmlEnum("message:ApprovalRequestData")]
		messageApprovalRequestData,
		[XmlEnum("message:VotingInformation")]
		messageVotingInformation,
		[XmlEnum("message:ReminderMessageData")]
		messageReminderMessageData,
		[XmlEnum("meeting:AssociatedCalendarItemId")]
		meetingAssociatedCalendarItemId,
		[XmlEnum("meeting:IsDelegated")]
		meetingIsDelegated,
		[XmlEnum("meeting:IsOutOfDate")]
		meetingIsOutOfDate,
		[XmlEnum("meeting:HasBeenProcessed")]
		meetingHasBeenProcessed,
		[XmlEnum("meeting:ResponseType")]
		meetingResponseType,
		[XmlEnum("meeting:ProposedStart")]
		meetingProposedStart,
		[XmlEnum("meeting:ProposedEnd")]
		meetingProposedEnd,
		[XmlEnum("meetingRequest:MeetingRequestType")]
		meetingRequestMeetingRequestType,
		[XmlEnum("meetingRequest:IntendedFreeBusyStatus")]
		meetingRequestIntendedFreeBusyStatus,
		[XmlEnum("meetingRequest:ChangeHighlights")]
		meetingRequestChangeHighlights,
		[XmlEnum("calendar:Start")]
		calendarStart,
		[XmlEnum("calendar:End")]
		calendarEnd,
		[XmlEnum("calendar:OriginalStart")]
		calendarOriginalStart,
		[XmlEnum("calendar:StartWallClock")]
		calendarStartWallClock,
		[XmlEnum("calendar:EndWallClock")]
		calendarEndWallClock,
		[XmlEnum("calendar:StartTimeZoneId")]
		calendarStartTimeZoneId,
		[XmlEnum("calendar:EndTimeZoneId")]
		calendarEndTimeZoneId,
		[XmlEnum("calendar:IsAllDayEvent")]
		calendarIsAllDayEvent,
		[XmlEnum("calendar:LegacyFreeBusyStatus")]
		calendarLegacyFreeBusyStatus,
		[XmlEnum("calendar:Location")]
		calendarLocation,
		[XmlEnum("calendar:EnhancedLocation")]
		calendarEnhancedLocation,
		[XmlEnum("calendar:When")]
		calendarWhen,
		[XmlEnum("calendar:IsMeeting")]
		calendarIsMeeting,
		[XmlEnum("calendar:IsCancelled")]
		calendarIsCancelled,
		[XmlEnum("calendar:IsRecurring")]
		calendarIsRecurring,
		[XmlEnum("calendar:MeetingRequestWasSent")]
		calendarMeetingRequestWasSent,
		[XmlEnum("calendar:IsResponseRequested")]
		calendarIsResponseRequested,
		[XmlEnum("calendar:CalendarItemType")]
		calendarCalendarItemType,
		[XmlEnum("calendar:MyResponseType")]
		calendarMyResponseType,
		[XmlEnum("calendar:Organizer")]
		calendarOrganizer,
		[XmlEnum("calendar:RequiredAttendees")]
		calendarRequiredAttendees,
		[XmlEnum("calendar:OptionalAttendees")]
		calendarOptionalAttendees,
		[XmlEnum("calendar:Resources")]
		calendarResources,
		[XmlEnum("calendar:ConflictingMeetingCount")]
		calendarConflictingMeetingCount,
		[XmlEnum("calendar:AdjacentMeetingCount")]
		calendarAdjacentMeetingCount,
		[XmlEnum("calendar:ConflictingMeetings")]
		calendarConflictingMeetings,
		[XmlEnum("calendar:AdjacentMeetings")]
		calendarAdjacentMeetings,
		[XmlEnum("calendar:Duration")]
		calendarDuration,
		[XmlEnum("calendar:TimeZone")]
		calendarTimeZone,
		[XmlEnum("calendar:AppointmentReplyTime")]
		calendarAppointmentReplyTime,
		[XmlEnum("calendar:AppointmentSequenceNumber")]
		calendarAppointmentSequenceNumber,
		[XmlEnum("calendar:AppointmentState")]
		calendarAppointmentState,
		[XmlEnum("calendar:Recurrence")]
		calendarRecurrence,
		[XmlEnum("calendar:FirstOccurrence")]
		calendarFirstOccurrence,
		[XmlEnum("calendar:LastOccurrence")]
		calendarLastOccurrence,
		[XmlEnum("calendar:ModifiedOccurrences")]
		calendarModifiedOccurrences,
		[XmlEnum("calendar:DeletedOccurrences")]
		calendarDeletedOccurrences,
		[XmlEnum("calendar:MeetingTimeZone")]
		calendarMeetingTimeZone,
		[XmlEnum("calendar:ConferenceType")]
		calendarConferenceType,
		[XmlEnum("calendar:AllowNewTimeProposal")]
		calendarAllowNewTimeProposal,
		[XmlEnum("calendar:IsOnlineMeeting")]
		calendarIsOnlineMeeting,
		[XmlEnum("calendar:MeetingWorkspaceUrl")]
		calendarMeetingWorkspaceUrl,
		[XmlEnum("calendar:NetShowUrl")]
		calendarNetShowUrl,
		[XmlEnum("calendar:UID")]
		calendarUID,
		[XmlEnum("calendar:RecurrenceId")]
		calendarRecurrenceId,
		[XmlEnum("calendar:DateTimeStamp")]
		calendarDateTimeStamp,
		[XmlEnum("calendar:StartTimeZone")]
		calendarStartTimeZone,
		[XmlEnum("calendar:EndTimeZone")]
		calendarEndTimeZone,
		[XmlEnum("calendar:JoinOnlineMeetingUrl")]
		calendarJoinOnlineMeetingUrl,
		[XmlEnum("calendar:OnlineMeetingSettings")]
		calendarOnlineMeetingSettings,
		[XmlEnum("calendar:IsOrganizer")]
		calendarIsOrganizer,
		[XmlEnum("task:ActualWork")]
		taskActualWork,
		[XmlEnum("task:AssignedTime")]
		taskAssignedTime,
		[XmlEnum("task:BillingInformation")]
		taskBillingInformation,
		[XmlEnum("task:ChangeCount")]
		taskChangeCount,
		[XmlEnum("task:Companies")]
		taskCompanies,
		[XmlEnum("task:CompleteDate")]
		taskCompleteDate,
		[XmlEnum("task:Contacts")]
		taskContacts,
		[XmlEnum("task:DelegationState")]
		taskDelegationState,
		[XmlEnum("task:Delegator")]
		taskDelegator,
		[XmlEnum("task:DueDate")]
		taskDueDate,
		[XmlEnum("task:IsAssignmentEditable")]
		taskIsAssignmentEditable,
		[XmlEnum("task:IsComplete")]
		taskIsComplete,
		[XmlEnum("task:IsRecurring")]
		taskIsRecurring,
		[XmlEnum("task:IsTeamTask")]
		taskIsTeamTask,
		[XmlEnum("task:Mileage")]
		taskMileage,
		[XmlEnum("task:Owner")]
		taskOwner,
		[XmlEnum("task:PercentComplete")]
		taskPercentComplete,
		[XmlEnum("task:Recurrence")]
		taskRecurrence,
		[XmlEnum("task:StartDate")]
		taskStartDate,
		[XmlEnum("task:Status")]
		taskStatus,
		[XmlEnum("task:StatusDescription")]
		taskStatusDescription,
		[XmlEnum("task:TotalWork")]
		taskTotalWork,
		[XmlEnum("contacts:Alias")]
		contactsAlias,
		[XmlEnum("contacts:AssistantName")]
		contactsAssistantName,
		[XmlEnum("contacts:Birthday")]
		contactsBirthday,
		[XmlEnum("contacts:BusinessHomePage")]
		contactsBusinessHomePage,
		[XmlEnum("contacts:Children")]
		contactsChildren,
		[XmlEnum("contacts:Companies")]
		contactsCompanies,
		[XmlEnum("contacts:CompanyName")]
		contactsCompanyName,
		[XmlEnum("contacts:CompleteName")]
		contactsCompleteName,
		[XmlEnum("contacts:ContactSource")]
		contactsContactSource,
		[XmlEnum("contacts:Culture")]
		contactsCulture,
		[XmlEnum("contacts:Department")]
		contactsDepartment,
		[XmlEnum("contacts:DisplayName")]
		contactsDisplayName,
		[XmlEnum("contacts:DirectoryId")]
		contactsDirectoryId,
		[XmlEnum("contacts:DirectReports")]
		contactsDirectReports,
		[XmlEnum("contacts:EmailAddresses")]
		contactsEmailAddresses,
		[XmlEnum("contacts:FileAs")]
		contactsFileAs,
		[XmlEnum("contacts:FileAsMapping")]
		contactsFileAsMapping,
		[XmlEnum("contacts:Generation")]
		contactsGeneration,
		[XmlEnum("contacts:GivenName")]
		contactsGivenName,
		[XmlEnum("contacts:ImAddresses")]
		contactsImAddresses,
		[XmlEnum("contacts:Initials")]
		contactsInitials,
		[XmlEnum("contacts:JobTitle")]
		contactsJobTitle,
		[XmlEnum("contacts:Manager")]
		contactsManager,
		[XmlEnum("contacts:ManagerMailbox")]
		contactsManagerMailbox,
		[XmlEnum("contacts:MiddleName")]
		contactsMiddleName,
		[XmlEnum("contacts:Mileage")]
		contactsMileage,
		[XmlEnum("contacts:MSExchangeCertificate")]
		contactsMSExchangeCertificate,
		[XmlEnum("contacts:Nickname")]
		contactsNickname,
		[XmlEnum("contacts:Notes")]
		contactsNotes,
		[XmlEnum("contacts:OfficeLocation")]
		contactsOfficeLocation,
		[XmlEnum("contacts:PhoneNumbers")]
		contactsPhoneNumbers,
		[XmlEnum("contacts:PhoneticFullName")]
		contactsPhoneticFullName,
		[XmlEnum("contacts:PhoneticFirstName")]
		contactsPhoneticFirstName,
		[XmlEnum("contacts:PhoneticLastName")]
		contactsPhoneticLastName,
		[XmlEnum("contacts:Photo")]
		contactsPhoto,
		[XmlEnum("contacts:PhysicalAddresses")]
		contactsPhysicalAddresses,
		[XmlEnum("contacts:PostalAddressIndex")]
		contactsPostalAddressIndex,
		[XmlEnum("contacts:Profession")]
		contactsProfession,
		[XmlEnum("contacts:SpouseName")]
		contactsSpouseName,
		[XmlEnum("contacts:Surname")]
		contactsSurname,
		[XmlEnum("contacts:WeddingAnniversary")]
		contactsWeddingAnniversary,
		[XmlEnum("contacts:UserSMIMECertificate")]
		contactsUserSMIMECertificate,
		[XmlEnum("contacts:HasPicture")]
		contactsHasPicture,
		[XmlEnum("distributionlist:Members")]
		distributionlistMembers,
		[XmlEnum("postitem:PostedTime")]
		postitemPostedTime,
		[XmlEnum("conversation:ConversationId")]
		conversationConversationId,
		[XmlEnum("conversation:ConversationTopic")]
		conversationConversationTopic,
		[XmlEnum("conversation:UniqueRecipients")]
		conversationUniqueRecipients,
		[XmlEnum("conversation:GlobalUniqueRecipients")]
		conversationGlobalUniqueRecipients,
		[XmlEnum("conversation:UniqueUnreadSenders")]
		conversationUniqueUnreadSenders,
		[XmlEnum("conversation:GlobalUniqueUnreadSenders")]
		conversationGlobalUniqueUnreadSenders,
		[XmlEnum("conversation:UniqueSenders")]
		conversationUniqueSenders,
		[XmlEnum("conversation:GlobalUniqueSenders")]
		conversationGlobalUniqueSenders,
		[XmlEnum("conversation:LastDeliveryTime")]
		conversationLastDeliveryTime,
		[XmlEnum("conversation:GlobalLastDeliveryTime")]
		conversationGlobalLastDeliveryTime,
		[XmlEnum("conversation:Categories")]
		conversationCategories,
		[XmlEnum("conversation:GlobalCategories")]
		conversationGlobalCategories,
		[XmlEnum("conversation:FlagStatus")]
		conversationFlagStatus,
		[XmlEnum("conversation:GlobalFlagStatus")]
		conversationGlobalFlagStatus,
		[XmlEnum("conversation:HasAttachments")]
		conversationHasAttachments,
		[XmlEnum("conversation:GlobalHasAttachments")]
		conversationGlobalHasAttachments,
		[XmlEnum("conversation:HasIrm")]
		conversationHasIrm,
		[XmlEnum("conversation:GlobalHasIrm")]
		conversationGlobalHasIrm,
		[XmlEnum("conversation:MessageCount")]
		conversationMessageCount,
		[XmlEnum("conversation:GlobalMessageCount")]
		conversationGlobalMessageCount,
		[XmlEnum("conversation:UnreadCount")]
		conversationUnreadCount,
		[XmlEnum("conversation:GlobalUnreadCount")]
		conversationGlobalUnreadCount,
		[XmlEnum("conversation:Size")]
		conversationSize,
		[XmlEnum("conversation:GlobalSize")]
		conversationGlobalSize,
		[XmlEnum("conversation:ItemClasses")]
		conversationItemClasses,
		[XmlEnum("conversation:GlobalItemClasses")]
		conversationGlobalItemClasses,
		[XmlEnum("conversation:Importance")]
		conversationImportance,
		[XmlEnum("conversation:GlobalImportance")]
		conversationGlobalImportance,
		[XmlEnum("conversation:ItemIds")]
		conversationItemIds,
		[XmlEnum("conversation:GlobalItemIds")]
		conversationGlobalItemIds,
		[XmlEnum("conversation:LastModifiedTime")]
		conversationLastModifiedTime,
		[XmlEnum("conversation:InstanceKey")]
		conversationInstanceKey,
		[XmlEnum("conversation:Preview")]
		conversationPreview,
		[XmlEnum("conversation:IconIndex")]
		conversationIconIndex,
		[XmlEnum("conversation:GlobalIconIndex")]
		conversationGlobalIconIndex,
		[XmlEnum("conversation:DraftItemIds")]
		conversationDraftItemIds,
		[XmlEnum("conversation:HasClutter")]
		conversationHasClutter,
		[XmlEnum("persona:PersonaId")]
		personaPersonaId,
		[XmlEnum("persona:PersonaType")]
		personaPersonaType,
		[XmlEnum("persona:GivenName")]
		personaGivenName,
		[XmlEnum("persona:CompanyName")]
		personaCompanyName,
		[XmlEnum("persona:Surname")]
		personaSurname,
		[XmlEnum("persona:DisplayName")]
		personaDisplayName,
		[XmlEnum("persona:EmailAddress")]
		personaEmailAddress,
		[XmlEnum("persona:FileAs")]
		personaFileAs,
		[XmlEnum("persona:HomeCity")]
		personaHomeCity,
		[XmlEnum("persona:CreationTime")]
		personaCreationTime,
		[XmlEnum("persona:RelevanceScore")]
		personaRelevanceScore,
		[XmlEnum("persona:WorkCity")]
		personaWorkCity,
		[XmlEnum("persona:PersonaObjectStatus")]
		personaPersonaObjectStatus,
		[XmlEnum("persona:FileAsId")]
		personaFileAsId,
		[XmlEnum("persona:DisplayNamePrefix")]
		personaDisplayNamePrefix,
		[XmlEnum("persona:YomiCompanyName")]
		personaYomiCompanyName,
		[XmlEnum("persona:YomiFirstName")]
		personaYomiFirstName,
		[XmlEnum("persona:YomiLastName")]
		personaYomiLastName,
		[XmlEnum("persona:Title")]
		personaTitle,
		[XmlEnum("persona:EmailAddresses")]
		personaEmailAddresses,
		[XmlEnum("persona:PhoneNumber")]
		personaPhoneNumber,
		[XmlEnum("persona:ImAddress")]
		personaImAddress,
		[XmlEnum("persona:ImAddresses")]
		personaImAddresses,
		[XmlEnum("persona:ImAddresses2")]
		personaImAddresses2,
		[XmlEnum("persona:ImAddresses3")]
		personaImAddresses3,
		[XmlEnum("persona:FolderIds")]
		personaFolderIds,
		[XmlEnum("persona:Attributions")]
		personaAttributions,
		[XmlEnum("persona:DisplayNames")]
		personaDisplayNames,
		[XmlEnum("persona:Initials")]
		personaInitials,
		[XmlEnum("persona:FileAses")]
		personaFileAses,
		[XmlEnum("persona:FileAsIds")]
		personaFileAsIds,
		[XmlEnum("persona:DisplayNamePrefixes")]
		personaDisplayNamePrefixes,
		[XmlEnum("persona:GivenNames")]
		personaGivenNames,
		[XmlEnum("persona:MiddleNames")]
		personaMiddleNames,
		[XmlEnum("persona:Surnames")]
		personaSurnames,
		[XmlEnum("persona:Generations")]
		personaGenerations,
		[XmlEnum("persona:Nicknames")]
		personaNicknames,
		[XmlEnum("persona:YomiCompanyNames")]
		personaYomiCompanyNames,
		[XmlEnum("persona:YomiFirstNames")]
		personaYomiFirstNames,
		[XmlEnum("persona:YomiLastNames")]
		personaYomiLastNames,
		[XmlEnum("persona:BusinessPhoneNumbers")]
		personaBusinessPhoneNumbers,
		[XmlEnum("persona:BusinessPhoneNumbers2")]
		personaBusinessPhoneNumbers2,
		[XmlEnum("persona:HomePhones")]
		personaHomePhones,
		[XmlEnum("persona:HomePhones2")]
		personaHomePhones2,
		[XmlEnum("persona:MobilePhones")]
		personaMobilePhones,
		[XmlEnum("persona:MobilePhones2")]
		personaMobilePhones2,
		[XmlEnum("persona:AssistantPhoneNumbers")]
		personaAssistantPhoneNumbers,
		[XmlEnum("persona:CallbackPhones")]
		personaCallbackPhones,
		[XmlEnum("persona:CarPhones")]
		personaCarPhones,
		[XmlEnum("persona:HomeFaxes")]
		personaHomeFaxes,
		[XmlEnum("persona:OrganizationMainPhones")]
		personaOrganizationMainPhones,
		[XmlEnum("persona:OtherFaxes")]
		personaOtherFaxes,
		[XmlEnum("persona:OtherTelephones")]
		personaOtherTelephones,
		[XmlEnum("persona:OtherPhones2")]
		personaOtherPhones2,
		[XmlEnum("persona:Pagers")]
		personaPagers,
		[XmlEnum("persona:RadioPhones")]
		personaRadioPhones,
		[XmlEnum("persona:TelexNumbers")]
		personaTelexNumbers,
		[XmlEnum("persona:WorkFaxes")]
		personaWorkFaxes,
		[XmlEnum("persona:Emails1")]
		personaEmails1,
		[XmlEnum("persona:Emails2")]
		personaEmails2,
		[XmlEnum("persona:Emails3")]
		personaEmails3,
		[XmlEnum("persona:BusinessHomePages")]
		personaBusinessHomePages,
		[XmlEnum("persona:School")]
		personaSchool,
		[XmlEnum("persona:PersonalHomePages")]
		personaPersonalHomePages,
		[XmlEnum("persona:OfficeLocations")]
		personaOfficeLocations,
		[XmlEnum("persona:BusinessAddresses")]
		personaBusinessAddresses,
		[XmlEnum("persona:HomeAddresses")]
		personaHomeAddresses,
		[XmlEnum("persona:OtherAddresses")]
		personaOtherAddresses,
		[XmlEnum("persona:Titles")]
		personaTitles,
		[XmlEnum("persona:Departments")]
		personaDepartments,
		[XmlEnum("persona:CompanyNames")]
		personaCompanyNames,
		[XmlEnum("persona:Managers")]
		personaManagers,
		[XmlEnum("persona:AssistantNames")]
		personaAssistantNames,
		[XmlEnum("persona:Professions")]
		personaProfessions,
		[XmlEnum("persona:SpouseNames")]
		personaSpouseNames,
		[XmlEnum("persona:Hobbies")]
		personaHobbies,
		[XmlEnum("persona:WeddingAnniversaries")]
		personaWeddingAnniversaries,
		[XmlEnum("persona:Birthdays")]
		personaBirthdays,
		[XmlEnum("persona:Children")]
		personaChildren,
		[XmlEnum("persona:Locations")]
		personaLocations,
		[XmlEnum("persona:ExtendedProperties")]
		personaExtendedProperties,
		[XmlEnum("persona:PostalAddress")]
		personaPostalAddress,
		[XmlEnum("persona:Bodies")]
		personaBodies
	}
}
