using System;

namespace Microsoft.Exchange.MailboxReplicationService
{
	internal enum MRSProxyCapabilities
	{
		PagedEnumeration,
		UpdateMovedMailboxReporting,
		Archives,
		ADUserXML,
		Push,
		InvokePreMoveAction,
		ProxyThrottling,
		CachedMailboxSyncState,
		MergeMailbox,
		ArchiveSeparation,
		DataGuarantee,
		PostMoveCleanup,
		AdvancedServerHealthCheck,
		MailboxOptions,
		ForceLogRoll,
		GetFolderRecFlags,
		SimpleExport,
		R5DC,
		NonMrsLogon,
		TenantHint = 24,
		PublicFolderMigration,
		ReleaseInfo,
		PublicFolderMove,
		LegacyResourceReservation,
		CopyToWithFlags = 30,
		SessionStatistics,
		InMailboxExternalRules,
		MailboxTableInfoFlags,
		ConfigRestore,
		DiscoverWellKnownFolders,
		MailboxReleaseCheck,
		ResourceReservation,
		IcsMidSetCheck,
		Pst,
		SetMessageProps,
		ConfigPst,
		ProxyConfiguration,
		MailboxCapabilities,
		Eas,
		FindServerByDatabaseOrMailbox,
		ContainerOperations,
		MailboxCapabilities2,
		ConfigPreferredADConnection,
		CanStoreCreatePFDumpster,
		CreateFolder3,
		ExtendedAclInformation,
		GetMailboxContainerMailboxes,
		ConfigEas2,
		ExportFolders,
		ConfigOlc,
		SetItemProperties,
		RemotePstExport,
		InternalAccessFolderCreation,
		SetMailboxSettings,
		MailboxRulesAclsCapabilities,
		PublicFolderMailboxesMigrationSupport = 82,
		MaxElement
	}
}
