using System;

namespace Microsoft.Exchange.MailboxReplicationService
{
	public enum RequestState
	{
		None,
		OverallMove,
		Queued,
		InProgress,
		InitializingMove,
		InitialSeeding,
		CreatingMailbox,
		CreatingFolderHierarchy,
		CreatingInitialSyncCheckpoint,
		LoadingMessages,
		CopyingMessages,
		Completion = 20,
		IncrementalSync,
		Finalization,
		DataReplicationWait = 24,
		ADUpdate,
		Cleanup = 23,
		Stalled = 30,
		StalledDueToHA,
		StalledDueToCI,
		StalledDueToMailboxLock,
		StalledDueToReadThrottle,
		StalledDueToWriteThrottle,
		StalledDueToReadCpu,
		StalledDueToWriteCpu,
		StalledDueToReadUnknown,
		StalledDueToWriteUnknown,
		TransientFailure,
		NetworkFailure,
		MDBOffline,
		ProxyBackoff,
		ServerBusyBackoff,
		Suspended = 50,
		AutoSuspended,
		InitialSeedingComplete,
		Idle = 57,
		Relinquished = 60,
		RelinquishedMDBFailover,
		RelinquishedDataGuarantee,
		RelinquishedHAStall,
		RelinquishedCIStall,
		RelinquishedWlmStall,
		Failed = 70,
		FailedBadItemLimit,
		FailedNetwork,
		FailedStallDueToHA,
		FailedStallDueToCI,
		FailedMAPI,
		FailedOther,
		FailedStuck,
		Completed = 100,
		CompletedWithWarnings,
		Canceled = 200,
		Removed = 300
	}
}
