using System;

namespace Microsoft.Exchange.MailboxReplicationService
{
	public enum WellKnownException
	{
		None,
		Exchange,
		Transient,
		MRS = 10,
		MRSTransient,
		MRSPermanent,
		MRSRemote = 20,
		MRSProxyLimitReached,
		MRSUpdateMovedMailbox,
		MRSUnableToFetchEasMessage,
		Obsolete_MRSSourceConnectionFailure,
		Obsolete_MRSTargetConnectionFailure,
		MRSUnableToReadPSTMessage,
		MRSUnableToCreatePSTMessage,
		MRSMailboxIsLocked,
		MRSUnableToGetPSTProps,
		Mapi,
		MapiRetryable,
		MapiPermanent,
		MapiMdbOffline = 40,
		MapiWrongServer,
		MapiVersion,
		MapiImportFailure,
		MapiCorruptData,
		MapiExiting,
		MapiLogonFailed,
		MapiCannotRegisterMapping,
		MapiNetworkError,
		MapiSessionLimit,
		MapiMaxObjectsExceeded,
		MapiShutoffQuotaExceeded,
		MapiCannotPreserveSignature,
		MapiNonCanonicalACL,
		MapiPartialCompletion,
		MapiMaxSubmissionExceeded,
		MapiInvalidParameter,
		MapiNotFound,
		MapiRpcBufferTooSmall,
		MapiNotEnoughMemory,
		MapiObjectChanged,
		MapiNoAccess,
		MapiMailboxInTransit,
		MapiADUnavailable,
		MapiObjectDeleted,
		MapiCorruptMidsetDeleted,
		Storage = 70,
		ConnectionFailedTransient = 80,
		StorageCannotMoveDefaultFolder,
		UnhealthyResource = 100,
		DataProviderTransient,
		DataProviderPermanent,
		NonCanonicalACL,
		WrongServer,
		CorruptData,
		ObjectNotFound,
		GlobalCounterRangeExceeded,
		ExArgumentOutOfRange,
		ExArgument,
		FxParser = 200,
		BufferParse,
		BufferTooSmall,
		ClientBackoff,
		CorruptRecipient,
		ResourceReservation = 300,
		ExpiredReservation,
		StaticCapacityExceededReservation,
		WlmCapacityExceededReservation,
		WlmResourceUnhealthy,
		AD = 400,
		ADOperation,
		ADTransient,
		InvalidMultivalueElement = 500,
		ConflictEntryIdCorruption,
		MrsOlcSettingNotImplemented = 600,
		MrsPropertyMismatch = 605,
		CommandExecution = 700
	}
}
