using System;

namespace Microsoft.Exchange.Security.RightsManagement
{
	internal enum RightsManagementFailureCode
	{
		Success,
		UnknownFailure = -1,
		InvalidLicense = -2147168512,
		InfoNotInLicense,
		InvalidLicenseSignature,
		EncryptionNotPermitted = -2147168508,
		UserRightNotGranted,
		InvalidVersion,
		InvalidEncodingType,
		InvalidNumericalValue,
		InvalidAlgorithmType,
		EnvironmentNotLoaded,
		EnvironmentCannotLoad,
		TooManyLoadedEnvironments,
		IncompatibleObjects = -2147168498,
		LibraryFail,
		EnablingPrincipalFailure,
		InfoNotPresent,
		BadGetInfoQuery,
		KeyTypeUnsupported,
		CryptoOperationUnsupported,
		ClockRollbackDetected,
		QueryReportsNoResults,
		UnexpectedException,
		BindValidityTimeViolated,
		BrokenCertChain,
		BindPolicyViolation = -2147168485,
		ManifestPolicyViolation = -2147183860,
		BindRevokedLicense = -2147168484,
		BindRevokedIssuer,
		BindRevokedPrincipal,
		BindRevokedResource,
		BindRevokedModule,
		BindContentNotInEndUseLicense,
		BindAccessPrincipalNotEnabling,
		BindAccessUnsatisfied,
		BindIndicatedPrincipalMissing,
		BindMachineNotFoundInGroupIdentity,
		LibraryUnsupportedPlugIn,
		BindRevocationListStale,
		BindNoApplicableRevocationList,
		InvalidHandle = -2147168468,
		BindIntervalTimeViolated = -2147168465,
		BindNoSatisfiedRightsGroup,
		BindSpecifiedWorkMissing,
		NoMoreData = -2147168461,
		LicenseAcquisitionFailed,
		IdMismatch,
		TooManyCertificates,
		NoDistributionPointUrlFound,
		AlreadyInProgress,
		GroupIdentityNotSet,
		RecordNotFound,
		NoConnect,
		NoLicense,
		NeedsMachineActivation,
		NeedsGroupIdentityActivation,
		ActivationFailed = -2147168448,
		Aborted,
		OutOfQuota,
		AuthenticationFailed,
		ServerError,
		InstallationFailed,
		HidCorrupted,
		InvalidServerResponse,
		ServiceNotFound,
		UseDefault,
		ServerNotFound,
		InvalidEmail,
		ValidityTimeViolation,
		OutdatedModule,
		ServiceMoved = -2147168421,
		ServiceGone,
		AdEntryNotFound,
		NotAChain,
		RequestDenied,
		InsufficientBuffer = -2147024774,
		NotSet = -2147168434,
		MetadataNotSet,
		RevocationInfoNotSet,
		InvalidTimeInfo,
		RightNotSet,
		LicenseBindingToWindowsIdentityFailed,
		InvalidIssuanceLicenseTemplate,
		InvalidKeyLength,
		ExpiredOfficialIssuanceLicenseTemplate = -2147168425,
		InvalidClientLicensorCertificate,
		HidInvalid,
		EmailNotVerified,
		DebuggerDetected = -2147168416,
		InvalidLockboxType = -2147168400,
		InvalidLockboxPath,
		InvalidRegistryPath,
		NoAesCryptoProvider,
		GlobalOptionAlreadySet,
		OwnerLicenseNotFound,
		InvalidWindow,
		WindowRegistrationFailed,
		SafeModeOSDetected,
		PlatformPolicyViolation,
		IssuanceLicenseLengthLimitExceeded = -2147168383,
		Completed = 315140,
		PreLicenseAcquisitionFailed = -2147160064,
		ClcAcquisitionFailed,
		RacAcquisitionFailed,
		TemplateAcquisitionFailed,
		UseLicenseAcquisitionFailed,
		FindServiceLocationFailed,
		InvalidTenantLicense,
		TemplateDoesNotExist,
		AttachmentProtectionFailed,
		FailedToExtractTargetUriFromMex,
		FailedToDownloadMexData,
		GetServerInfoFailed,
		InternalLicensingDisabled,
		ExternalLicensingDisabled,
		BindInsufficientRightsToCreateEncryptor,
		InvalidRightsAccountCertificate,
		BadDRMPropsSignature,
		UnknownDRMFailure,
		NotEnoughRightsToReEncrypt,
		ExtractNotAllowed,
		ExchangeMisConfiguration,
		InvalidRecipient,
		FederationNotEnabled,
		FailedToDetermineExchangeMode,
		FederatedMailboxNotSet,
		FailedToRequestDelegationToken,
		FederationCertificateAccessFailure,
		ActiveFederationFault,
		ActionNotSupported,
		MessageSecurityError,
		CommunicationError,
		OperationTimeout,
		InvalidCertificateChain,
		InvalidBlackBox,
		InvalidIssuanceLicense,
		UnauthorizedAccess,
		UntrustedRightsLabel,
		PreCertificationFailed,
		ClusterDecommissioned,
		EnablingBitsUnsupported,
		InvalidPersonaCertificate,
		Http3xxFailure,
		ConnectFailure,
		TrustFailure,
		HttpUnauthorizedFailure,
		HttpForbiddenFailure,
		HttpNotFoundFailure,
		ADUserNotFound,
		ADUserNotFederated,
		OfflineRmsServerFailure,
		ServerRightNotGranted,
		InvalidLicensee,
		FeatureDisabled,
		NotSupported,
		CorruptData,
		MissingLicense,
		InvalidLicensingLocation,
		ExpiredLicense
	}
}
