using System;
using System.ComponentModel;

namespace Microsoft.Exchange.Data
{
	internal enum InferredImportanceReason : uint
	{
		[Description("FeatureBias")]
		FeatureBias,
		[Description("UserOverride")]
		UserOverride,
		[Description("IsMarkedHighImportanceBySender")]
		IsMarkedHighImportanceBySender,
		[Description("IsMarkedLowImportanceBySender")]
		IsMarkedLowImportanceBySender,
		[Description("SenderIsYou")]
		SenderIsYou,
		[Description("ConversationStarterIsYou")]
		ConversationStarterIsYou,
		[Description("OnlyRecipient")]
		OnlyRecipient,
		[Description("IsFlagged")]
		IsFlagged,
		[Description("HasAttachment")]
		HasAttachment,
		[Description("SenderIsManager")]
		SenderIsManager,
		[Description("SenderIsDirectReport")]
		SenderIsDirectReport,
		[Description("SenderIsAutomated")]
		SenderIsAutomated,
		[Description("HasMultipleRecipients")]
		HasMultipleRecipients,
		[Description("SubjectPrefix")]
		SubjectPrefix,
		[Description("SubjectContent")]
		SubjectContent,
		[Description("RecipientPosition")]
		RecipientPosition,
		[Description("ConversationContributions")]
		ConversationContributions,
		[Description("ManagerPosition")]
		ManagerPosition,
		[Description("RecipientCountOnToLine")]
		RecipientCountOnToLine,
		[Description("RecipientCountOnCcLine")]
		RecipientCountOnCcLine,
		[Description("ReplyToAMessageFromMe")]
		ReplyToAMessageFromMe,
		[Description("PreviousUnread")]
		PreviousUnread,
		[Description("PreviousFlagged")]
		PreviousFlagged,
		[Description("SwitchedToToLineFirstTime")]
		SwitchedToToLineFirstTime,
		[Description("ItemClass")]
		ItemClass,
		[Description("IsResponseRequested")]
		IsResponseRequested,
		[Description("NumberOfFileAttachments")]
		NumberOfFileAttachments,
		[Description("NumberOfMessageAttachments")]
		NumberOfMessageAttachments,
		[Description("NumberOfInlineAttachments")]
		NumberOfInlineAttachments,
		[Description("NewSender")]
		NewSender,
		[Description("NewConversationStarter")]
		NewConversationStarter,
		[Description("TimeSinceLastSentToSender")]
		TimeSinceLastSentToSender,
		[Description("IsTaskPresent")]
		IsTaskPresent,
		[Description("IsMeetingPresent")]
		IsMeetingPresent,
		[Description("IsQuestionPresent")]
		IsQuestionPresent,
		[Description("QuestionWithRecipientOntheToOrCcLine")]
		QuestionWithRecipientOntheToOrCcLine,
		[Description("SubjectLength")]
		SubjectLength,
		[Description("UniqueBodyLength")]
		UniqueBodyLength,
		[Description("WordsInUniqueBody")]
		WordsInUniqueBody,
		[Description("BigramsInUniqueBody")]
		BigramsInUniqueBody,
		[Description("IsEndOfConversation")]
		IsEndOfConversation,
		[Description("Sender")]
		Sender = 2147483648U,
		[Description("SenderCc")]
		SenderCc,
		[Description("ConversationStarter")]
		ConversationStarter = 2147483664U,
		[Description("ConversationStarterCc")]
		ConversationStarterCc,
		[Description("Keywords")]
		Keywords = 2147483904U,
		[Description("SenderDList")]
		SenderDList,
		[Description("ConversationStarterDList")]
		ConversationStarterDList = 2147483920U,
		[Description("RecipientOnToLine")]
		RecipientOnToLine,
		[Description("RecipientOnCcLine")]
		RecipientOnCcLine = 2147487744U
	}
}
