using System;
using System.CodeDom.Compiler;
using System.Xml.Serialization;

namespace Microsoft.Exchange.SoapWebClient.EWS
{
	[XmlType(Namespace = "http://schemas.microsoft.com/exchange/services/2006/messages", IncludeInSchema = false)]
	[GeneratedCode("wsdl", "4.0.30319.17627")]
	[Serializable]
	public enum ItemsChoiceType4
	{
		ApplyConversationActionResponseMessage,
		ArchiveItemResponseMessage,
		ConvertIdResponseMessage,
		CopyFolderResponseMessage,
		CopyItemResponseMessage,
		CreateAttachmentResponseMessage,
		CreateFolderPathResponseMessage,
		CreateFolderResponseMessage,
		CreateItemResponseMessage,
		CreateManagedFolderResponseMessage,
		CreateUserConfigurationResponseMessage,
		DeleteAttachmentResponseMessage,
		DeleteFolderResponseMessage,
		DeleteItemResponseMessage,
		DeleteUserConfigurationResponseMessage,
		EmptyFolderResponseMessage,
		ExpandDLResponseMessage,
		ExportItemsResponseMessage,
		FindFolderResponseMessage,
		FindItemResponseMessage,
		FindMailboxStatisticsByKeywordsResponseMessage,
		FindPeopleResponseMessage,
		GetAppManifestsResponseMessage,
		GetAttachmentResponseMessage,
		GetClientAccessTokenResponseMessage,
		GetClientExtensionResponseMessage,
		GetConversationItemsResponseMessage,
		GetDiscoverySearchConfigurationResponseMessage,
		GetEncryptionConfigurationResponseMessage,
		GetEventsResponseMessage,
		GetFolderResponseMessage,
		GetHoldOnMailboxesResponseMessage,
		GetItemResponseMessage,
		GetNonIndexableItemDetailsResponseMessage,
		GetNonIndexableItemStatisticsResponseMessage,
		GetPasswordExpirationDateResponse,
		GetPersonaResponseMessage,
		GetRemindersResponse,
		GetRoomListsResponse,
		GetRoomsResponse,
		GetSearchableMailboxesResponseMessage,
		GetServerTimeZonesResponseMessage,
		GetSharingFolderResponseMessage,
		GetSharingMetadataResponseMessage,
		GetStreamingEventsResponseMessage,
		GetUserConfigurationResponseMessage,
		GetUserPhotoResponseMessage,
		GetUserRetentionPolicyTagsResponseMessage,
		MarkAllItemsAsReadResponseMessage,
		MarkAsJunkResponseMessage,
		MoveFolderResponseMessage,
		MoveItemResponseMessage,
		PerformReminderActionResponse,
		PostModernGroupItemResponseMessage,
		RefreshSharingFolderResponseMessage,
		ResolveNamesResponseMessage,
		SearchMailboxesResponseMessage,
		SendItemResponseMessage,
		SendNotificationResponseMessage,
		SetClientExtensionResponseMessage,
		SetEncryptionConfigurationResponseMessage,
		SetHoldOnMailboxesResponseMessage,
		SubscribeResponseMessage,
		SyncFolderHierarchyResponseMessage,
		SyncFolderItemsResponseMessage,
		UnsubscribeResponseMessage,
		UpdateFolderResponseMessage,
		UpdateGroupMailboxResponseMessage,
		UpdateItemInRecoverableItemsResponseMessage,
		UpdateItemResponseMessage,
		UpdateMailboxAssociationResponseMessage,
		UpdateUserConfigurationResponseMessage,
		UploadItemsResponseMessage
	}
}
