using System;

namespace Microsoft.Exchange.Rpc.LogSearch
{
	internal static class LogSearchErrorCode
	{
		// Note: this type is marked as 'beforefieldinit'.
		static LogSearchErrorCode()
		{
			LogSearchErrorCode.LOGSEARCH_E_RPC_SERVER_UNAVAILABLE = 1722;
			LogSearchErrorCode.LOGSEARCH_E_LOG_UNKNOWN_LOG = -2147220991;
			LogSearchErrorCode.LOGSEARCH_E_UNKNOWN_SESSION_ID = -2147220990;
			LogSearchErrorCode.LOGSEARCH_E_INVALID_QUERY_CONDITION = -2147220989;
			LogSearchErrorCode.LOGSEARCH_E_MISSING_QUERY_CONDITION = -2147220988;
			LogSearchErrorCode.LOGSEARCH_E_UNBOUND_QUERY_VARIABLE = -2147220987;
			LogSearchErrorCode.LOGSEARCH_E_UNRECOGNIZED_QUERY_FIELD = -2147220986;
			LogSearchErrorCode.LOGSEARCH_E_INCOMPATIBLE_QUERY_OPERAND_TYPES = -2147220985;
			LogSearchErrorCode.LOGSEARCH_E_DUPLICATE_BOUND_VARIABLE_DECLARATION = -2147220984;
			LogSearchErrorCode.LOGSEARCH_E_SERVER_TOO_BUSY = -2147220983;
			LogSearchErrorCode.LOGSEARCH_E_RESPONSE_OVERFLOW = -2147220982;
			LogSearchErrorCode.LOGSEARCH_E_BAD_QUERY_XML = -2147220981;
			LogSearchErrorCode.LOGSEARCH_E_MISSING_BOUND_VARIABLE_NAME = -2147220980;
			LogSearchErrorCode.LOGSEARCH_E_INVALID_OPERAND_CLASS = -2147220979;
			LogSearchErrorCode.LOGSEARCH_E_QUERY_TOO_COMPLEX = -2147220978;
			LogSearchErrorCode.LOGSEARCH_E_SESSION_CANCELED = -2147220977;
		}

		public static int LOGSEARCH_E_LOG_UNKNOWN_LOG;

		public static int LOGSEARCH_E_UNKNOWN_SESSION_ID;

		public static int LOGSEARCH_E_INVALID_QUERY_CONDITION;

		public static int LOGSEARCH_E_MISSING_QUERY_CONDITION;

		public static int LOGSEARCH_E_UNBOUND_QUERY_VARIABLE;

		public static int LOGSEARCH_E_UNRECOGNIZED_QUERY_FIELD;

		public static int LOGSEARCH_E_INCOMPATIBLE_QUERY_OPERAND_TYPES;

		public static int LOGSEARCH_E_DUPLICATE_BOUND_VARIABLE_DECLARATION;

		public static int LOGSEARCH_E_SERVER_TOO_BUSY;

		public static int LOGSEARCH_E_RESPONSE_OVERFLOW;

		public static int LOGSEARCH_E_BAD_QUERY_XML;

		public static int LOGSEARCH_E_MISSING_BOUND_VARIABLE_NAME;

		public static int LOGSEARCH_E_INVALID_OPERAND_CLASS;

		public static int LOGSEARCH_E_QUERY_TOO_COMPLEX;

		public static int LOGSEARCH_E_SESSION_CANCELED;

		public static int LOGSEARCH_E_RPC_SERVER_UNAVAILABLE = 1722;

		public static int LOGSEARCH_E_ENDPOINT_NOT_REGISTERED = 1753;
	}
}
