using System;
using Microsoft.Exchange.Core.RuleTasks;

namespace Microsoft.Exchange.MessagingPolicies.Rules.Tasks
{
	public enum ADAttribute
	{
		[LocDescription(RulesTasksStrings.IDs.ADAttributeName)]
		DisplayName,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeFirstName)]
		FirstName,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeInitials)]
		Initials,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeLastName)]
		LastName,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeOffice)]
		Office,
		[LocDescription(RulesTasksStrings.IDs.ADAttributePhoneNumber)]
		PhoneNumber,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeOtherPhoneNumber)]
		OtherPhoneNumber,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeEmail)]
		Email,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeStreet)]
		Street,
		[LocDescription(RulesTasksStrings.IDs.ADAttributePOBox)]
		POBox,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCity)]
		City,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeState)]
		State,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeZipCode)]
		ZipCode,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCountry)]
		Country,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeUserLogonName)]
		UserLogonName,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeHomePhoneNumber)]
		HomePhoneNumber,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeOtherHomePhoneNumber)]
		OtherHomePhoneNumber,
		[LocDescription(RulesTasksStrings.IDs.ADAttributePagerNumber)]
		PagerNumber,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeMobileNumber)]
		MobileNumber,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeFaxNumber)]
		FaxNumber,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeOtherFaxNumber)]
		OtherFaxNumber,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeNotes)]
		Notes,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeTitle)]
		Title,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeDepartment)]
		Department,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCompany)]
		Company,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeManager)]
		Manager,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute1)]
		CustomAttribute1,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute2)]
		CustomAttribute2,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute3)]
		CustomAttribute3,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute4)]
		CustomAttribute4,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute5)]
		CustomAttribute5,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute6)]
		CustomAttribute6,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute7)]
		CustomAttribute7,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute8)]
		CustomAttribute8,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute9)]
		CustomAttribute9,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute10)]
		CustomAttribute10,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute11)]
		CustomAttribute11,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute12)]
		CustomAttribute12,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute13)]
		CustomAttribute13,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute14)]
		CustomAttribute14,
		[LocDescription(RulesTasksStrings.IDs.ADAttributeCustomAttribute15)]
		CustomAttribute15
	}
}
