using System;
using System.Xml.Serialization;

namespace Microsoft.Exchange.Services.Core.Types
{
	[XmlType(TypeName = "UnindexedFieldURIType", Namespace = "http://schemas.microsoft.com/exchange/services/2006/types")]
	[Serializable]
	public enum PropertyUriEnum
	{
		[XmlEnum("folder:FolderId")]
		FolderId,
		[XmlEnum("folder:ParentFolderId")]
		ParentFolderId,
		[XmlEnum("folder:DisplayName")]
		FolderDisplayName,
		[XmlEnum("folder:UnreadCount")]
		UnreadCount,
		[XmlEnum("folder:TotalCount")]
		TotalCount,
		[XmlEnum("folder:ChildFolderCount")]
		ChildFolderCount,
		[XmlEnum("folder:FolderClass")]
		FolderClass,
		[XmlEnum("folder:SearchParameters")]
		SearchParameters,
		[XmlEnum("folder:ManagedFolderInformation")]
		ManagedFolderInformation,
		[XmlEnum("folder:PermissionSet")]
		PermissionSet,
		[XmlEnum("folder:EffectiveRights")]
		FolderEffectiveRights,
		[XmlEnum("folder:SharingEffectiveRights")]
		FolderSharingEffectiveRights,
		[XmlEnum("folder:DistinguishedFolderId")]
		DistinguishedFolderId,
		[XmlEnum("folder:PolicyTag")]
		FolderPolicyTag,
		[XmlEnum("folder:ArchiveTag")]
		FolderArchiveTag,
		[XmlEnum("folder:UnClutteredViewFolderEntryId")]
		UnClutteredViewFolderEntryId,
		[XmlEnum("folder:ClutteredViewFolderEntryId")]
		ClutteredViewFolderEntryId,
		[XmlEnum("folder:ClutterCount")]
		ClutterCount,
		[XmlEnum("folder:UnreadClutterCount")]
		UnreadClutterCount,
		[XmlEnum("folder:ReplicaList")]
		ReplicaList,
		[XmlEnum("item:ItemId")]
		ItemId,
		[XmlEnum("item:ParentFolderId")]
		ItemParentId,
		[XmlEnum("item:ItemClass")]
		ItemClass,
		[XmlEnum("item:MimeContent")]
		MimeContent,
		[XmlEnum("item:Attachments")]
		Attachments,
		[XmlEnum("item:Subject")]
		Subject,
		[XmlEnum("item:DateTimeReceived")]
		DateTimeReceived,
		[XmlEnum("item:Size")]
		Size,
		[XmlEnum("item:Categories")]
		Categories,
		[XmlEnum("item:HasAttachments")]
		HasAttachments,
		[XmlEnum("item:Importance")]
		Importance,
		[XmlEnum("item:InReplyTo")]
		InReplyTo,
		[XmlEnum("item:InternetMessageHeaders")]
		InternetMessageHeaders,
		[XmlEnum("item:IsAssociated")]
		IsAssociated,
		[XmlEnum("item:IsDraft")]
		IsDraft,
		[XmlEnum("item:IsFromMe")]
		IsFromMe,
		[XmlEnum("item:IsResend")]
		IsResend,
		[XmlEnum("item:IsSubmitted")]
		IsSubmitted,
		[XmlEnum("item:IsUnmodified")]
		IsUnmodified,
		[XmlEnum("item:DateTimeSent")]
		DateTimeSent,
		[XmlEnum("item:DateTimeCreated")]
		DateTimeCreated,
		[XmlEnum("item:Body")]
		Body,
		[XmlEnum("item:ResponseObjects")]
		ResponseObjects,
		[XmlEnum("item:Sensitivity")]
		Sensitivity,
		[XmlEnum("item:ReminderDueBy")]
		ReminderDueBy,
		[XmlEnum("item:ReminderIsSet")]
		ReminderIsSet,
		[XmlEnum("item:ReminderNextTime")]
		ReminderNextTime,
		[XmlEnum("item:ReminderMinutesBeforeStart")]
		ReminderMinutesBeforeStart,
		[XmlEnum("item:DisplayTo")]
		DisplayTo,
		[XmlEnum("item:DisplayCc")]
		DisplayCc,
		[XmlEnum("item:Culture")]
		Culture,
		[XmlEnum("item:EffectiveRights")]
		ItemEffectiveRights,
		[XmlEnum("item:LastModifiedName")]
		LastModifiedName,
		[XmlEnum("item:LastModifiedTime")]
		ItemLastModifiedTime,
		[XmlEnum("item:WebClientReadFormQueryString")]
		WebClientReadFormQueryString,
		[XmlEnum("item:WebClientEditFormQueryString")]
		WebClientEditFormQueryString,
		[XmlEnum("item:ConversationId")]
		ConversationId,
		[XmlEnum("item:UniqueBody")]
		UniqueBody,
		[XmlEnum("item:PredictedActionReasons")]
		PredictedActionReasons,
		[XmlEnum("item:IsClutter")]
		IsClutter,
		[XmlEnum("item:Flag")]
		Flag,
		[XmlEnum("item:StoreEntryId")]
		StoreEntryId,
		[XmlEnum("item:InstanceKey")]
		InstanceKey,
		[XmlEnum("item:NormalizedBody")]
		NormalizedBody,
		[XmlEnum("item:EntityExtractionResult")]
		EntityExtractionResult,
		[XmlEnum("item:PolicyTag")]
		ItemPolicyTag,
		[XmlEnum("item:ArchiveTag")]
		ItemArchiveTag,
		[XmlEnum("item:RetentionDate")]
		ItemRetentionDate,
		[XmlEnum("item:Preview")]
		Preview,
		[XmlEnum("item:RightsManagementLicenseData")]
		RightsManagementLicenseData,
		[XmlEnum("item:BlockStatus")]
		BlockStatus,
		[XmlEnum("item:HasBlockedImages")]
		HasBlockedImages,
		[XmlEnum("item:TextBody")]
		TextBody,
		[XmlEnum("item:IconIndex")]
		IconIndex,
		[XmlEnum("item:ModernReminders")]
		ModernReminders,
		[XmlEnum("item:WorkingSetSourcePartition")]
		WorkingSetSourcePartition,
		[XmlEnum("item:ReceivedOrRenewTime")]
		ReceivedOrRenewTime,
		[XmlEnum("item:RenewTime")]
		RenewTime,
		[XmlEnum("item:MimeContentUTF8")]
		MimeContentUTF8,
		[XmlEnum("message:ConversationIndex")]
		ConversationIndex,
		[XmlEnum("message:ConversationTopic")]
		ConversationTopic,
		[XmlEnum("message:InternetMessageId")]
		InternetMessageId,
		[XmlEnum("message:IsRead")]
		IsRead,
		[XmlEnum("message:IsResponseRequested")]
		IsResponseRequested,
		[XmlEnum("message:IsReadReceiptRequested")]
		IsReadReceiptRequested,
		[XmlEnum("message:IsDeliveryReceiptRequested")]
		IsDeliveryReceiptRequested,
		[XmlEnum("message:ReceivedBy")]
		ReceivedBy,
		[XmlEnum("message:ReceivedRepresenting")]
		ReceivedRepresenting,
		[XmlEnum("message:References")]
		References,
		[XmlEnum("message:ReplyTo")]
		ReplyTo,
		[XmlEnum("message:From")]
		From,
		[XmlEnum("message:Sender")]
		Sender,
		[XmlEnum("message:ToRecipients")]
		ToRecipients,
		[XmlEnum("message:CcRecipients")]
		CcRecipients,
		[XmlEnum("message:BccRecipients")]
		BccRecipients,
		[XmlEnum("message:ApprovalRequestData")]
		ApprovalRequestData,
		[XmlEnum("message:VotingInformation")]
		VotingInformation,
		[XmlEnum("message:ReminderMessageData")]
		ReminderMessageData,
		[XmlEnum("message:MailboxGuid")]
		MailboxGuid,
		[XmlEnum("message:RecipientCounts")]
		RecipientCounts,
		[XmlEnum("message:IsGroupEscalationMessage")]
		IsGroupEscalationMessage,
		[XmlEnum("meeting:AssociatedCalendarItemId")]
		AssociatedCalendarItemId,
		[XmlEnum("meeting:IsDelegated")]
		IsDelegated,
		[XmlEnum("meeting:IsOutOfDate")]
		IsOutOfDate,
		[XmlEnum("meeting:HasBeenProcessed")]
		HasBeenProcessed,
		[XmlEnum("meeting:ResponseType")]
		ResponseType,
		[XmlEnum("meeting:ProposedStart")]
		ProposedStart,
		[XmlEnum("meeting:ProposedEnd")]
		ProposedEnd,
		[XmlEnum("meetingRequest:MeetingRequestType")]
		MeetingRequestType,
		[XmlEnum("meetingRequest:IntendedFreeBusyStatus")]
		IntendedFreeBusyStatus,
		[XmlEnum("meetingRequest:ChangeHighlights")]
		ChangeHighlights,
		[XmlEnum("calendar:Start")]
		Start,
		[XmlEnum("calendar:End")]
		End,
		[XmlEnum("calendar:StartWallClock")]
		StartWallClock,
		[XmlEnum("calendar:EndWallClock")]
		EndWallClock,
		[XmlEnum("calendar:EnhancedLocation")]
		EnhancedLocation,
		[XmlEnum("calendar:OriginalStart")]
		OriginalStart,
		[XmlEnum("calendar:IsAllDayEvent")]
		IsAllDayEvent,
		[XmlEnum("calendar:LegacyFreeBusyStatus")]
		LegacyFreeBusyStatus,
		[XmlEnum("calendar:Location")]
		Location,
		[XmlEnum("calendar:When")]
		When,
		[XmlEnum("calendar:IsOrganizer")]
		IsOrganizer,
		[XmlEnum("calendar:IsMeeting")]
		IsMeeting,
		[XmlEnum("calendar:IsCancelled")]
		IsCancelled,
		[XmlEnum("calendar:IsSeriesCancelled")]
		IsSeriesCancelled,
		[XmlEnum("calendar:IsRecurring")]
		IsRecurring,
		[XmlEnum("calendar:MeetingRequestWasSent")]
		MeetingRequestWasSent,
		[XmlEnum("calendar:IsResponseRequested")]
		CalendarIsResponseRequested,
		[XmlEnum("calendar:CalendarItemType")]
		CalendarItemType,
		[XmlEnum("calendar:MyResponseType")]
		MyResponseType,
		[XmlEnum("calendar:Organizer")]
		Organizer,
		[XmlEnum("calendar:RequiredAttendees")]
		RequiredAttendees,
		[XmlEnum("calendar:OptionalAttendees")]
		OptionalAttendees,
		[XmlEnum("calendar:Resources")]
		Resources,
		[XmlEnum("calendar:AttendeeCounts")]
		AttendeeCounts,
		[XmlEnum("calendar:ConflictingMeetingCount")]
		ConflictingMeetingCount,
		[XmlEnum("calendar:AdjacentMeetingCount")]
		AdjacentMeetingCount,
		[XmlEnum("calendar:ConflictingMeetings")]
		ConflictingMeetings,
		[XmlEnum("calendar:AdjacentMeetings")]
		AdjacentMeetings,
		[XmlEnum("calendar:Duration")]
		Duration,
		[XmlEnum("calendar:TimeZone")]
		TimeZone,
		[XmlEnum("calendar:AppointmentReplyTime")]
		AppointmentReplyTime,
		[XmlEnum("calendar:AppointmentReplyName")]
		AppointmentReplyName,
		[XmlEnum("calendar:AppointmentSequenceNumber")]
		AppointmentSequenceNumber,
		[XmlEnum("calendar:AppointmentState")]
		AppointmentState,
		[XmlEnum("calendar:Recurrence")]
		Recurrence,
		[XmlEnum("calendar:FirstOccurrence")]
		FirstOccurrence,
		[XmlEnum("calendar:LastOccurrence")]
		LastOccurrence,
		[XmlEnum("calendar:ModifiedOccurrences")]
		ModifiedOccurrences,
		[XmlEnum("calendar:DeletedOccurrences")]
		DeletedOccurrences,
		[XmlEnum("calendar:MeetingTimeZone")]
		MeetingTimeZone,
		[XmlEnum("calendar:StartTimeZone")]
		StartTimeZone,
		[XmlEnum("calendar:EndTimeZone")]
		EndTimeZone,
		[XmlEnum("calendar:StartTimeZoneId")]
		StartTimeZoneId,
		[XmlEnum("calendar:EndTimeZoneId")]
		EndTimeZoneId,
		[XmlEnum("calendar:ConferenceType")]
		ConferenceType,
		[XmlEnum("calendar:AllowNewTimeProposal")]
		AllowNewTimeProposal,
		[XmlEnum("calendar:IsOnlineMeeting")]
		IsOnlineMeeting,
		[XmlEnum("calendar:MeetingWorkspaceUrl")]
		MeetingWorkspaceUrl,
		[XmlEnum("calendar:NetShowUrl")]
		NetShowUrl,
		[XmlEnum("calendar:UID")]
		UID,
		[XmlEnum("calendar:RecurrenceId")]
		RecurrenceId,
		[XmlEnum("calendar:DateTimeStamp")]
		DateTimeStamp,
		[XmlEnum("calendar:JoinOnlineMeetingUrl")]
		JoinOnlineMeetingUrl,
		[XmlEnum("calendar:OnlineMeetingSettings")]
		OnlineMeetingSettings,
		[XmlEnum("calendar:InboxReminders")]
		InboxReminders,
		[XmlEnum("task:ActualWork")]
		TaskActualWork,
		[XmlEnum("task:AssignedTime")]
		TaskAssignedTime,
		[XmlEnum("task:BillingInformation")]
		TaskBillingInformation,
		[XmlEnum("task:ChangeCount")]
		TaskChangeCount,
		[XmlEnum("task:Companies")]
		TaskCompanies,
		[XmlEnum("task:CompleteDate")]
		TaskCompleteDate,
		[XmlEnum("task:Contacts")]
		TaskContacts,
		[XmlEnum("task:DelegationState")]
		TaskDelegationState,
		[XmlEnum("task:Delegator")]
		TaskDelegator,
		[XmlEnum("task:DueDate")]
		TaskDueDate,
		[XmlEnum("task:IsAssignmentEditable")]
		TaskIsAssignmentEditable,
		[XmlEnum("task:IsComplete")]
		TaskIsComplete,
		[XmlEnum("task:IsRecurring")]
		TaskIsTaskRecurring,
		[XmlEnum("task:IsTeamTask")]
		TaskIsTeamTask,
		[XmlEnum("task:Mileage")]
		TaskMileage,
		[XmlEnum("task:Owner")]
		TaskOwner,
		[XmlEnum("task:PercentComplete")]
		TaskPercentComplete,
		[XmlEnum("task:Recurrence")]
		TaskRecurrence,
		[XmlEnum("task:StartDate")]
		TaskStartDate,
		[XmlEnum("task:Status")]
		TaskStatus,
		[XmlEnum("task:StatusDescription")]
		TaskStatusDescription,
		[XmlEnum("task:TotalWork")]
		TaskTotalWork,
		[XmlEnum("task:DoItTime")]
		TaskDoItTime,
		[XmlEnum("contacts:Alias")]
		Alias,
		[XmlEnum("contacts:AssistantName")]
		AssistantName,
		[XmlEnum("contacts:Birthday")]
		Birthday,
		[XmlEnum("contacts:BirthdayLocal")]
		BirthdayLocal,
		[XmlEnum("contacts:BusinessHomePage")]
		BusinessHomePage,
		[XmlEnum("contacts:Children")]
		Children,
		[XmlEnum("contacts:Companies")]
		Companies,
		[XmlEnum("contacts:CompanyName")]
		CompanyName,
		[XmlEnum("contacts:CompleteName")]
		CompleteName,
		[XmlEnum("contacts:ContactSource")]
		ContactSource,
		[XmlEnum("contacts:Culture")]
		ContactCulture,
		[XmlEnum("contacts:Department")]
		Department,
		[XmlEnum("contacts:DirectoryId")]
		DirectoryId,
		[XmlEnum("contacts:DirectReports")]
		DirectReports,
		[XmlEnum("contacts:DisplayName")]
		DisplayName,
		[XmlEnum("contacts:EmailAddresses")]
		EmailAddresses,
		[XmlEnum("contacts:FileAs")]
		FileAs,
		[XmlEnum("contacts:FileAsMapping")]
		FileAsMapping,
		[XmlEnum("contacts:Generation")]
		Generation,
		[XmlEnum("contacts:GivenName")]
		GivenName,
		[XmlEnum("contacts:ImAddresses")]
		ImAddresses,
		[XmlEnum("contacts:Initials")]
		Initials,
		[XmlEnum("contacts:JobTitle")]
		JobTitle,
		[XmlEnum("contacts:Manager")]
		Manager,
		[XmlEnum("contacts:ManagerMailbox")]
		ManagerMailbox,
		[XmlEnum("contacts:MiddleName")]
		MiddleName,
		[XmlEnum("contacts:Mileage")]
		Mileage,
		[XmlEnum("contacts:MSExchangeCertificate")]
		MSExchangeCertificate,
		[XmlEnum("contacts:Nickname")]
		Nickname,
		[XmlEnum("contacts:Notes")]
		Notes,
		[XmlEnum("contacts:OfficeLocation")]
		OfficeLocation,
		[XmlEnum("contacts:PhoneNumbers")]
		PhoneNumbers,
		[XmlEnum("contacts:PhoneticFullName")]
		PhoneticFullName,
		[XmlEnum("contacts:PhoneticFirstName")]
		PhoneticFirstName,
		[XmlEnum("contacts:PhoneticLastName")]
		PhoneticLastName,
		[XmlEnum("contacts:Photo")]
		Photo,
		[XmlEnum("contacts:PhysicalAddresses")]
		PhysicalAddresses,
		[XmlEnum("contacts:PostalAddressIndex")]
		PostalAddressIndex,
		[XmlEnum("contacts:Profession")]
		Profession,
		[XmlEnum("contacts:SpouseName")]
		SpouseName,
		[XmlEnum("contacts:Surname")]
		Surname,
		[XmlEnum("contacts:WeddingAnniversary")]
		WeddingAnniversary,
		[XmlEnum("contacts:WeddingAnniversaryLocal")]
		WeddingAnniversaryLocal,
		[XmlEnum("contacts:UserSMIMECertificate")]
		UserSMIMECertificate,
		[XmlEnum("contacts:HasPicture")]
		HasPicture,
		[XmlEnum("conversation:ConversationId")]
		ConversationGuidId,
		[XmlEnum("conversation:ConversationTopic")]
		Topic,
		[XmlEnum("conversation:UniqueRecipients")]
		ConversationUniqueRecipients,
		[XmlEnum("conversation:GlobalUniqueRecipients")]
		ConversationGlobalUniqueRecipients,
		[XmlEnum("conversation:UniqueUnreadSenders")]
		ConversationUniqueUnreadSenders,
		[XmlEnum("conversation:GlobalUniqueUnreadSenders")]
		ConversationGlobalUniqueUnreadSenders,
		[XmlEnum("conversation:UniqueSenders")]
		ConversationUniqueSenders,
		[XmlEnum("conversation:GlobalUniqueSenders")]
		ConversationGlobalUniqueSenders,
		[XmlEnum("conversation:LastDeliveryTime")]
		ConversationLastDeliveryTime,
		[XmlEnum("conversation:GlobalLastDeliveryTime")]
		ConversationGlobalLastDeliveryTime,
		[XmlEnum("conversation:Categories")]
		ConversationCategories,
		[XmlEnum("conversation:GlobalCategories")]
		ConversationGlobalCategories,
		[XmlEnum("conversation:FlagStatus")]
		ConversationFlagStatus,
		[XmlEnum("conversation:GlobalFlagStatus")]
		ConversationGlobalFlagStatus,
		[XmlEnum("conversation:HasAttachments")]
		ConversationHasAttachments,
		[XmlEnum("conversation:GlobalHasAttachments")]
		ConversationGlobalHasAttachments,
		[XmlEnum("conversation:HasIrm")]
		ConversationHasIrm,
		[XmlEnum("conversation:GlobalHasIrm")]
		ConversationGlobalHasIrm,
		[XmlEnum("conversation:MessageCount")]
		ConversationMessageCount,
		[XmlEnum("conversation:GlobalMessageCount")]
		ConversationGlobalMessageCount,
		[XmlEnum("conversation:UnreadCount")]
		ConversationUnreadCount,
		[XmlEnum("conversation:GlobalUnreadCount")]
		ConversationGlobalUnreadCount,
		[XmlEnum("conversation:Size")]
		ConversationSize,
		[XmlEnum("conversation:GlobalSize")]
		ConversationGlobalSize,
		[XmlEnum("conversation:ItemClasses")]
		ConversationItemClasses,
		[XmlEnum("conversation:GlobalItemClasses")]
		ConversationGlobalItemClasses,
		[XmlEnum("conversation:Importance")]
		ConversationImportance,
		[XmlEnum("conversation:GlobalImportance")]
		ConversationGlobalImportance,
		[XmlEnum("conversation:ItemIds")]
		ConversationItemIds,
		[XmlEnum("conversation:GlobalItemIds")]
		ConversationGlobalItemIds,
		[XmlEnum("conversation:LastModifiedTime")]
		ConversationLastModifiedTime,
		[XmlEnum("conversation:InstanceKey")]
		ConversationInstanceKey,
		[XmlEnum("conversation:Preview")]
		ConversationPreview,
		[XmlEnum("conversation:IconIndex")]
		ConversationIconIndex,
		[XmlEnum("conversation:GlobalIconIndex")]
		ConversationGlobalIconIndex,
		[XmlEnum("conversation:DraftItemIds")]
		ConversationDraftItemIds,
		[XmlEnum("conversation:HasClutter")]
		ConversationHasClutter,
		[XmlEnum("conversation:InitialPost")]
		ConversationInitialPost,
		[XmlEnum("conversation:RecentReplys")]
		ConversationRecentReplys,
		[XmlEnum("conversation:WorkingSetSourcePartition")]
		ConversationWorkingSetSourcePartition,
		[XmlEnum("conversation:FamilyId")]
		FamilyId,
		[XmlEnum("distributionlist:Members")]
		Members,
		[XmlEnum("postitem:PostedTime")]
		PostedTime,
		[XmlEnum("persona:GivenName")]
		PersonaGivenName,
		[XmlEnum("persona:DisplayName")]
		PersonaDisplayName,
		[XmlEnum("persona:Surname")]
		PersonaSurname,
		[XmlEnum("persona:CompanyName")]
		PersonaCompanyName,
		[XmlEnum("persona:CompanyNameSortKey")]
		PersonaCompanyNameSortKey,
		[XmlEnum("persona:FileAs")]
		PersonaFileAs,
		[XmlEnum("persona:CreationTime")]
		PersonaCreationTime,
		[XmlEnum("persona:IsFavorite")]
		PersonaIsFavorite,
		[XmlEnum("persona:WorkCity")]
		PersonaWorkCity,
		[XmlEnum("persona:WorkCitySortKey")]
		PersonaWorkCitySortKey,
		[XmlEnum("persona:DisplayNameFirstLast")]
		PersonaDisplayNameFirstLast,
		[XmlEnum("persona:DisplayNameFirstLastSortKey")]
		PersonaDisplayNameFirstLastSortKey,
		[XmlEnum("persona:DisplayNameFirstLastHeader")]
		PersonaDisplayNameFirstLastHeader,
		[XmlEnum("persona:DisplayNameLastFirst")]
		PersonaDisplayNameLastFirst,
		[XmlEnum("persona:DisplayNameLastFirstHeader")]
		PersonaDisplayNameLastFirstHeader,
		[XmlEnum("persona:DisplayNameLastFirstSortKey")]
		PersonaDisplayNameLastFirstSortKey,
		[XmlEnum("persona:PersonaId")]
		PersonaId,
		[XmlEnum("persona:PersonaType")]
		PersonaType,
		[XmlEnum("persona:PersonaObjectStatus")]
		PersonaObjectStatus,
		[XmlEnum("persona:FileAsId")]
		PersonaFileAsId,
		[XmlEnum("persona:DisplayNamePrefix")]
		PersonaDisplayNamePrefix,
		[XmlEnum("persona:YomiCompanyName")]
		PersonaYomiCompanyName,
		[XmlEnum("persona:YomiFirstName")]
		PersonaYomiFirstName,
		[XmlEnum("persona:YomiLastName")]
		PersonaYomiLastName,
		[XmlEnum("persona:Title")]
		PersonaTitle,
		[XmlEnum("persona:EmailAddress")]
		PersonaEmailAddress,
		[XmlEnum("persona:EmailAddresses")]
		PersonaEmailAddresses,
		[XmlEnum("persona:PhoneNumber")]
		PersonaPhoneNumber,
		[XmlEnum("persona:ImAddress")]
		PersonaImAddress,
		[XmlEnum("persona:ImAddresses")]
		PersonaImAddresses,
		[XmlEnum("persona:ImAddresses2")]
		PersonaImAddresses2,
		[XmlEnum("persona:ImAddresses3")]
		PersonaImAddresses3,
		[XmlEnum("persona:HomeCity")]
		PersonaHomeCity,
		[XmlEnum("persona:HomeCitySortKey")]
		PersonaHomeCitySortKey,
		[XmlEnum("persona:FolderIds")]
		PersonaFolderIds,
		[XmlEnum("persona:Attributions")]
		PersonaAttributions,
		[XmlEnum("persona:DisplayNames")]
		PersonaDisplayNames,
		[XmlEnum("persona:Initials")]
		PersonaInitials,
		[XmlEnum("persona:FileAses")]
		PersonaFileAses,
		[XmlEnum("persona:FileAsIds")]
		PersonaFileAsIds,
		[XmlEnum("persona:DisplayNamePrefixes")]
		PersonaDisplayNamePrefixes,
		[XmlEnum("persona:GivenNames")]
		PersonaGivenNames,
		[XmlEnum("persona:MiddleName")]
		PersonaMiddleName,
		[XmlEnum("persona:MiddleNames")]
		PersonaMiddleNames,
		[XmlEnum("persona:Surnames")]
		PersonaSurnames,
		[XmlEnum("persona:Generation")]
		PersonaGeneration,
		[XmlEnum("persona:Generations")]
		PersonaGenerations,
		[XmlEnum("persona:Nickname")]
		PersonaNickname,
		[XmlEnum("persona:Nicknames")]
		PersonaNicknames,
		[XmlEnum("persona:Alias")]
		PersonaAlias,
		[XmlEnum("persona:UnreadCount")]
		PersonaUnreadCount,
		[XmlEnum("persona:YomiCompanyNames")]
		PersonaYomiCompanyNames,
		[XmlEnum("persona:YomiFirstNames")]
		PersonaYomiFirstNames,
		[XmlEnum("persona:YomiLastNames")]
		PersonaYomiLastNames,
		[XmlEnum("persona:BusinessPhoneNumbers")]
		PersonaBusinessPhoneNumbers,
		[XmlEnum("persona:BusinessPhoneNumbers2")]
		PersonaBusinessPhoneNumbers2,
		[XmlEnum("persona:HomePhones")]
		PersonaHomePhones,
		[XmlEnum("persona:HomePhones2")]
		PersonaHomePhones2,
		[XmlEnum("persona:MobilePhones")]
		PersonaMobilePhones,
		[XmlEnum("persona:MobilePhones2")]
		PersonaMobilePhones2,
		[XmlEnum("persona:AssistantPhoneNumbers")]
		PersonaAssistantPhoneNumbers,
		[XmlEnum("persona:CallbackPhones")]
		PersonaCallbackPhones,
		[XmlEnum("persona:CarPhones")]
		PersonaCarPhones,
		[XmlEnum("persona:HomeFaxes")]
		PersonaHomeFaxes,
		[XmlEnum("persona:OrganizationMainPhones")]
		PersonaOrganizationMainPhones,
		[XmlEnum("persona:OtherFaxes")]
		PersonaOtherFaxes,
		[XmlEnum("persona:OtherTelephones")]
		PersonaOtherTelephones,
		[XmlEnum("persona:OtherPhones2")]
		PersonaOtherPhones2,
		[XmlEnum("persona:Pagers")]
		PersonaPagers,
		[XmlEnum("persona:RadioPhones")]
		PersonaRadioPhones,
		[XmlEnum("persona:TelexNumbers")]
		PersonaTelexNumbers,
		[XmlEnum("persona:TTYTDDPhoneNumbers")]
		PersonaTTYTDDPhoneNumbers,
		[XmlEnum("persona:WorkFaxes")]
		PersonaWorkFaxes,
		[XmlEnum("persona:Emails1")]
		PersonaEmails1,
		[XmlEnum("persona:Emails1DisplayNames")]
		PersonaEmails1DisplayNames,
		[XmlEnum("persona:Emails1OriginalDisplayNames")]
		PersonaEmails1OriginalDisplayNames,
		[XmlEnum("persona:Emails2")]
		PersonaEmails2,
		[XmlEnum("persona:Emails2DisplayNames")]
		PersonaEmails2DisplayNames,
		[XmlEnum("persona:Emails2OriginalDisplayNames")]
		PersonaEmails2OriginalDisplayNames,
		[XmlEnum("persona:Emails3")]
		PersonaEmails3,
		[XmlEnum("persona:Emails3DisplayNames")]
		PersonaEmails3DisplayNames,
		[XmlEnum("persona:Emails3OriginalDisplayNames")]
		PersonaEmails3OriginalDisplayNames,
		[XmlEnum("persona:BusinessHomePages")]
		PersonaBusinessHomePages,
		[XmlEnum("persona:School")]
		PersonaSchools,
		[XmlEnum("persona:PersonalHomePages")]
		PersonaPersonalHomePages,
		[XmlEnum("persona:OfficeLocations")]
		PersonaOfficeLocations,
		[XmlEnum("persona:BusinessAddresses")]
		PersonaBusinessAddresses,
		[XmlEnum("persona:HomeAddresses")]
		PersonaHomeAddresses,
		[XmlEnum("persona:OtherAddresses")]
		PersonaOtherAddresses,
		[XmlEnum("persona:Titles")]
		PersonaTitles,
		[XmlEnum("persona:Department")]
		PersonaDepartment,
		[XmlEnum("persona:Departments")]
		PersonaDepartments,
		[XmlEnum("persona:CompanyNames")]
		PersonaCompanyNames,
		[XmlEnum("persona:Managers")]
		PersonaManagers,
		[XmlEnum("persona:AssistantNames")]
		PersonaAssistantNames,
		[XmlEnum("persona:Professions")]
		PersonaProfessions,
		[XmlEnum("persona:SpouseNames")]
		PersonaSpouseNames,
		[XmlEnum("persona:Hobbies")]
		PersonaHobbies,
		[XmlEnum("persona:WeddingAnniversaries")]
		PersonaWeddingAnniversaries,
		[XmlEnum("persona:WeddingAnniversariesLocal")]
		PersonaWeddingAnniversariesLocal,
		[XmlEnum("persona:Birthdays")]
		PersonaBirthdays,
		[XmlEnum("persona:BirthdaysLocal")]
		PersonaBirthdaysLocal,
		[XmlEnum("persona:Children")]
		PersonaChildren,
		[XmlEnum("persona:Location")]
		PersonaLocation,
		[XmlEnum("persona:Locations")]
		PersonaLocations,
		[XmlEnum("persona:ExtendedProperties")]
		PersonaExtendedProperties,
		[XmlEnum("persona:ADObjectId")]
		PersonaADObjectId,
		[XmlEnum("persona:PostalAddress")]
		PersonaPostalAddress,
		[XmlEnum("persona:RelevanceScore")]
		PersonaRelevanceScore,
		[XmlEnum("persona:Bodies")]
		PersonaBodies,
		[XmlEnum("persona:Members")]
		PersonaMembers,
		[XmlEnum("persona:ThirdPartyPhotoUrls")]
		PersonaThirdPartyPhotoUrls,
		[XmlEnum("message:RelyOnConversationIndex")]
		RelyOnConversationIndex,
		[XmlEnum("message:IsSpecificMessageReplyStamped")]
		IsSpecificMessageReplyStamped,
		[XmlEnum("message:IsSpecificMessageReply")]
		IsSpecificMessageReply,
		[XmlEnum("item:SupportsSideConversation")]
		SupportsSideConversation,
		[XmlEnum("conversation:GlobalLastDeliveryOrRenewTime")]
		ConversationGlobalLastDeliveryOrRenewTime,
		[XmlEnum("message:LikeCount")]
		LikeCount,
		[XmlEnum("item:RichContent")]
		RichContent,
		[XmlEnum("conversation:GlobalRichContent")]
		ConversationGlobalRichContent,
		[XmlEnum("conversation:ConversationMailboxGuid")]
		ConversationMailboxGuid,
		[XmlEnum("conversation:ConversationGlobalPreview")]
		ConversationGlobalPreview,
		[XmlEnum("conversation:LastDeliveryOrRenewTime")]
		ConversationLastDeliveryOrRenewTime,
		[XmlEnum("message:Likers")]
		Likers
	}
}
