using System;
using System.Net;
using System.Xml.Serialization;
using Microsoft.Exchange.Services.OData;

namespace Microsoft.Exchange.Services.Core.Types
{
	[XmlType(TypeName = "ResponseCodeType", Namespace = "http://schemas.microsoft.com/exchange/services/2006/messages")]
	[Serializable]
	public enum ResponseCodeType
	{
		NoError,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorAccessDenied,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorAccessModeSpecified,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorAccountDisabled,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorAddDelegatesFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorADOperation,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorADSessionFilter,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorADUnavailable,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorArchiveFolderPathCreation,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorAffectedTaskOccurrencesRequired,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorAggregatedAccountLimitReached,
		[ODataHttpStatusCode(HttpStatusCode.Conflict)]
		ErrorAggregatedAccountAlreadyExists,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorAccountNotSupportedForAggregation,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorServerTemporaryUnavailable,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorAttachmentNestLevelLimitExceeded,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorAttachmentSizeLimitExceeded,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorBatchProcessingStopped,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarCannotMoveOrCopyOccurrence,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarCannotUpdateDeletedItem,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarCannotUseIdForOccurrenceId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarCannotUseIdForRecurringMasterId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarDurationIsTooLong,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarEndDateIsEarlierThanStartDate,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarFolderIsInvalidForCalendarView,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarInvalidAttributeValue,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarInvalidDayForTimeChangePattern,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarInvalidDayForWeeklyRecurrence,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarInvalidPropertyState,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarInvalidPropertyValue,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarInvalidRecurrence,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarInvalidTimeZone,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsDelegatedForAccept,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsDelegatedForDecline,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsDelegatedForRemove,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsDelegatedForTentative,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsGroupMailboxForAccept,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsGroupMailboxForDecline,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsGroupMailboxForTentative,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsGroupMailboxForSuppressReadReceipt,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsNotOrganizer,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsOrganizerForAccept,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsOrganizerForDecline,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsOrganizerForRemove,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsOrganizerForTentative,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsCancelledForAccept,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsCancelledForDecline,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsCancelledForRemove,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsCancelledForTentative,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarIsCancelledMessageSent,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarOccurrenceIndexIsOutOfRecurrenceRange,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarOccurrenceIsDeletedFromRecurrence,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarOutOfRange,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarMeetingRequestIsOutOfDate,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarMeetingIsOutOfDateResponseNotProcessed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarMeetingIsOutOfDateResponseNotProcessedMessageSent,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCalendarViewRangeTooBig,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCallerIsInvalidADAccount,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotAddAggregatedAccount,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotAddAggregatedAccountMailbox,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotAddAggregatedAccountToList,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotGetAggregatedAccount,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotRemoveAggregatedAccount,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotRemoveAggregatedAccountMailbox,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotSetAggregatedAccount,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotArchiveCalendarContactTaskFolderException,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotArchiveItemsInArchiveMailbox,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotArchiveItemsInPublicFolders,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotCreateCalendarItemInNonCalendarFolder,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotCreateContactInNonContactFolder,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotCreatePostItemInNonMailFolder,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotCreateTaskInNonTaskFolder,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotCreateUnifiedMailbox,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotFindUnifiedMailbox,
		ErrorCannotFindUser,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotDeleteObject,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotDeleteTaskOccurrence,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotGetSourceFolderPath,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotLinkMoreThanOneO365AccountToAnMsa,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotOpenFileAttachment,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotResolveOrganizationName,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCannotSetCalendarPermissionOnNonCalendarFolder,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCannotSetNonCalendarPermissionOnCalendarFolder,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCannotSetPermissionUnknownEntries,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCannotSpecifySearchFolderAsSourceFolder,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCannotUseFolderIdForItemId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCannotUseItemIdForFolderId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorChangeKeyRequired,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorChangeKeyRequiredForWriteOperations,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorConnectionFailed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorContainsFilterWrongType,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorContentConversionFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorContentIndexingNotEnabled,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCorruptData,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorCreateItemAccessDenied,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorCreateSubfolderAccessDenied,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorCrossMailboxMoveCopy,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCrossSiteRequest,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorDataSizeLimitExceeded,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorDataSourceOperation,
		[ODataHttpStatusCode(HttpStatusCode.Conflict)]
		ErrorDelegateAlreadyExists,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorDelegateCannotAddOwner,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorDelegateMissingConfiguration,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorDelegateNoUser,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorDelegateValidationFailed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorDeleteDistinguishedFolder,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorDeleteItemsFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorDeleteUnifiedMessagingPromptFailed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorDistinguishedUserNotSupported,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorDistributionListMemberNotExist,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorDuplicateInputFolderNames,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorDuplicateUserIdsSpecified,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorExchangeApplicationNotEnabled,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorExceededConnectionCount,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorExceededFindCountLimit,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorExceededSubscriptionCount,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidContactEmailAddress,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidContactEmailIndex,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidManagedFolderProperty,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingManagedFolderId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidArgument,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidAggregatedAccountCredentials,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidLogonType,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidMailbox,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidManagedFolderQuota,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidManagedFolderSize,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPermissionSettings,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidProxySecurityContext,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidUnifiedViewParameter,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidUserInfo,
		ErrorMailboxIsNotPartOfAggregatedMailboxes,
		ErrorMailboxContainerGuidMismatch,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorManagedFolderNotFound,
		[ODataHttpStatusCode(HttpStatusCode.Conflict)]
		ErrorManagedFolderAlreadyExists,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCreateManagedFolderPartialCompletion,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorManagedFoldersRootFailure,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorEmailAddressMismatch,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorEventNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorExpiredSubscription,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorFolderCorrupt,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorFolderNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorFolderPropertRequestFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorFolderSave,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorFolderSaveFailed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorFolderSavePropertyError,
		[ODataHttpStatusCode(HttpStatusCode.Conflict)]
		ErrorFolderExists,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorFoldersMustBelongToSameMailbox,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorImContactLimitReached,
		[ODataHttpStatusCode(HttpStatusCode.Conflict)]
		ErrorImGroupDisplayNameAlreadyExists,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorImGroupLimitReached,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorImpersonateUserDenied,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorImpersonationDenied,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorImpersonationFailed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorIncorrectSchemaVersion,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorIncorrectUpdatePropertyCount,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInsufficientResources,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInternalServerError,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInternalServerTransientError,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidAttachmentId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidAttachmentSubfilter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidAttachmentSubfilterTextFilter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidChangeKey,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidCompleteDate,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidDelegatePermission,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidDelegateUserId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidExcludesRestriction,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidExpressionTypeForSubFilter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidExtendedProperty,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidExtendedPropertyValue,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidFederatedOrganizationId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidFolderId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidFolderTypeForOperation,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidFractionalPagingParameters,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIdEmpty,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIdMalformed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIdMalformedEwsLegacyIdFormat,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIdMonikerTooLong,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIdNotAnItemAttachmentId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIdStoreObjectIdTooLong,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIdReturnedByResolveNames,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIdTooManyAttachmentLevels,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIdXml,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidImContactId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidImDistributionGroupSmtpAddress,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidImGroupId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidIndexedPagingParameters,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidInternetHeaderChildNodes,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationCreateItemAttachment,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationArchiveItem,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationCreateItem,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationAcceptItem,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationDeclineItem,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationCancelItem,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationExpandDL,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationRemoveItem,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationSendItem,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidItemForOperationTentative,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidOofParameter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidNameForNameResolution,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidOperation,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPagingMaxRows,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidParentFolder,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPercentCompleteValue,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPhoneCallId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPhoneNumber,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPropertyAppend,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPropertyDelete,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPropertyForExists,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPropertyRequest,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPropertySet,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPropertyForOperation,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPropertyUpdateSentMessage,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPullSubscriptionId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidPushSubscriptionUrl,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRecipients,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRecipientSubfilter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRecipientSubfilterComparison,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRecipientSubfilterOrder,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRecipientSubfilterTextFilter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidReferenceItem,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRequest,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRestriction,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRetentionTagTypeMismatch,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRetentionTagInvisible,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRetentionTagInheritance,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRetentionTagIdGuid,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRoutingType,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidScheduledOofDuration,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSchemaVersionForMailboxVersion,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSendItemSaveSettings,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidSerializedAccessToken,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidServerVersion,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSid,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSIPUri,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSubfilterType,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSubfilterTypeNotAttendeeType,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSubfilterTypeNotRecipientType,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSubscription,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSubscriptionRequest,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSyncStateData,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidUserOofSettings,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidUserPrincipalName,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidUser,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidParameter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidUserSid,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidUserSidMissingUPN,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidValueForCountSystemQueryOption,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidValueForProperty,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidWatermark,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorIPGatewayNotFound,
		[ODataHttpStatusCode(HttpStatusCode.Conflict)]
		ErrorIrresolvableConflict,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorItemCorrupt,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorItemNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorItemPropertyRequestFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorItemSave,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorItemSavePropertyError,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMailboxConfiguration,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMailboxHoldNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMailboxMoveInProgress,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMailboxStoreUnavailable,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMailTipsDisabled,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMessageDispositionRequired,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMessageSizeExceeded,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMimeContentConversionFailed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMimeContentInvalid,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMimeContentInvalidBase64String,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingEmailAddress,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingEmailAddressForManagedFolder,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingInformationEmailAddress,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingInformationReferenceItemId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingItemForCreateItemAttachment,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingRecipients,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingUserIdInformation,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMoreThanOneAccessModeSpecified,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMoveCopyFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMoveDistinguishedFolder,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMultiLegacyMailboxAccess,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNameResolutionMultipleResults,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNameResolutionNoMailbox,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNameResolutionNoResults,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNewEventStreamConnectionOpened,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoApplicableProxyCASServersAvailable,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoDestinationCASDueToKerberosRequirements,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoDestinationCASDueToSSLRequirements,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoDestinationCASDueToVersionMismatch,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoFolderClassOverride,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorNonExistentMailbox,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNonPrimarySmtpAddress,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoPropertyTagForCustomProperties,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoPublicFolderReplicaAvailable,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoRespondingCASInDestinationSite,
		[ODataHttpStatusCode(HttpStatusCode.NotAcceptable)]
		ErrorNotAcceptable,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNotApplicableOutsideOfDatacenter,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNotEnoughMemory,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNotDelegate,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorObjectTypeChanged,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorOccurrenceCrossingBoundary,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorOccurrenceTimeSpanTooBig,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorOperationNotAllowedWithPublicFolderRoot,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorParentFolderIdRequired,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorParentFolderNotFound,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorPasswordChangeRequired,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorPasswordExpired,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPeopleConnectFailedToReadApplicationConfiguration,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPeopleConnectionNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPeopleConnectionNoToken,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPhoneNumberNotDialable,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPropertyUpdate,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPromptPublishingOperationFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPropertyValidationFailure,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorProxiedSubscriptionCallFailure,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorProxyGroupSidLimitExceeded,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorProxyCallFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorProxyServiceDiscoveryFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorProxyTokenExpired,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPublicFolderMailboxDiscoveryFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPublicFolderOperationFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPublicFolderSyncException,
		[ODataHttpStatusCode(HttpStatusCode.ServiceUnavailable)]
		ErrorMultifactorRegistrationUnavailable,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidProperty,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidUrlQuery,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidUrlQueryFilter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorQueryFilterTooLong,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorQuotaExceeded,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorReadEventsFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorReadReceiptNotPending,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorRecurrenceEndDateTooBig,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorRecurrenceHasNoOccurrence,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorRequiredPropertyMissing,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorResolveNamesInvalidFolderType,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorResolveNamesOnlyOneContactsFolderAllowed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorRemoveDelegatesFailed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorResponseSchemaValidation,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorRestrictionTooLong,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorRestrictionTooComplex,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidExchangeImpersonationHeaderData,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorSavedItemFolderNotFound,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorSchemaValidation,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSearchFolderNotInitialized,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorSendAsDenied,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSendMeetingCancellationsRequired,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSendMeetingInvitationsOrCancellationsRequired,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSendMeetingInvitationsRequired,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSentMeetingRequestUpdate,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSentTaskRequestUpdate,
		[ODataHttpStatusCode(HttpStatusCode.ServiceUnavailable)]
		ErrorServerBusy,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorStaleObject,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSubmissionQuotaExceeded,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorSubscriptionAccessDenied,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSubscriptionDelegateAccessNotSupported,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorSubscriptionNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSubscriptionUnsubscribed,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorSyncFolderNotFound,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorTeamMailboxNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorTeamMailboxNotLinkedToSharePoint,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorTeamMailboxUrlValidationFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorTeamMailboxNotAuthorizedOwner,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorTeamMailboxActiveToPendingDelete,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorTeamMailboxFailedSendingNotifications,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorTeamMailboxErrorUnknown,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorTimeZone,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorToFolderNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorTokenSerializationDenied,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorTooManyObjectsOpened,
		[ODataHttpStatusCode(HttpStatusCode.Conflict)]
		ErrorUnifiedMailboxAlreadyExists,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUpdateDelegatesFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUpdatePropertyMismatch,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUnableToGetUserOofSettings,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUnableToRemoveImContactFromGroup,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUnifiedMailboxSupportedOnlyWithMicrosoftAccount,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUnifiedMessagingDialPlanNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUnifiedMessagingReportDataNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUnifiedMessagingPromptNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUnifiedMessagingRequestFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUnifiedMessagingServerNotFound,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedSubFilter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedCulture,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedMapiPropertyType,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedMimeConversion,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedPathForQuery,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedPathForSortGroup,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedPropertyDefinition,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedQueryFilter,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedRecurrence,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorUnsupportedTypeForConversion,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUserNotUnifiedMessagingEnabled,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorValueOutOfRange,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorVirusDetected,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorVirusMessageDeleted,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorVoiceMailNotImplemented,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorWrongServerVersion,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorWrongServerVersionDelegate,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSharingSynchronizationFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSharingNoExternalEwsAvailable,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidGetSharingFolderRequest,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorNotAllowedExternalSharingByPolicy,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorUserNotAllowedByPolicy,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorPermissionNotAllowedByPolicy,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorOrganizationNotFederated,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidExternalSharingInitiator,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUserWithoutFederatedProxyAddress,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidExternalSharingSubscriber,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidSharingData,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidSharingMessage,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNotSupportedSharingMessage,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorTooManyContactsException,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorFullSyncRequiredException,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorClientIntentInvalidStateDefinition,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorClientIntentNotFound,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorRequestStreamTooBig = 5000,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMailboxDataArrayEmpty,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMailboxDataArrayTooBig,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorTimeIntervalTooBig,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidMergedFreeBusyInterval,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorResultSetTooBig = 5006,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidClientSecurityContext,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorMailboxLogonFailed,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorMailRecipientNotFound,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidTimeInterval,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorPublicFolderServerNotFound,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorInvalidAccessLevel,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSecurityDescriptor,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorWin32InteropError,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorProxyRequestNotAllowed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorProxyRequestProcessingFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorPublicFolderRequestProcessingFailed,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorWorkingHoursXmlMalformed = 5019,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorServiceDiscoveryFailed = 5021,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorAddressSpaceNotFound = 5023,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorAvailabilityConfigNotFound,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidCrossForestCredentials,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidFreeBusyViewType,
		[ODataHttpStatusCode(HttpStatusCode.RequestTimeout)]
		ErrorTimeoutExpired,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingArgument,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorNoCalendar,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoConnectionSettingsAvailableForAggregatedAccount,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidAuthorizationContext = 5032,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorLogonAsNetworkServiceFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidNetworkServiceContext,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidSmtpAddress,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorIndividualMailboxLimitReached,
		[ODataHttpStatusCode(HttpStatusCode.Forbidden)]
		ErrorNoFreeBusyAccess,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorClientDisconnected = 5042,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorAutoDiscoverFailed = 5039,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMeetingSuggestionGenerationFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorFreeBusyGenerationFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorFreeBusyDLLimitReached = 5043,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMailboxFailover = 5046,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidOrganizationRelationshipForFreeBusy,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorRemoteUserMailboxMustSpecifyExplicitLocalMailbox,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMissingInformationSharingFolderId,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorDuplicateSOAPHeader,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMessageTrackingPermanentError,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMessageTrackingTransientError,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorMessageTrackingNoSuchDomain,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorApplyConversationActionFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotEmptyFolder,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInboxRulesValidationError,
		[ODataHttpStatusCode(HttpStatusCode.Conflict)]
		ErrorOutlookRuleBlobExists,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorRulesOverQuota,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorDuplicateLegacyDistinguishedName,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMissedNotificationEvents,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorRightsManagementPermanentException,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorRightsManagementTransientException,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorExchangeConfigurationException,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidClientAccessTokenRequest,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorNoSpeechDetected,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorUMServerUnavailable,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorRecipientNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorRecognizerNotInstalled,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorSpeechGrammarError,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidManagementRoleHeader,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorLocationServicesDisabled,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorLocationServicesRequestTimedOut,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorLocationServicesRequestFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorLocationServicesInvalidRequest,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorWeatherServiceDisabled,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorMailboxScopeNotAllowedWithoutQueryString,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorArchiveMailboxSearchFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorGetRemoteArchiveFolderFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorFindRemoteArchiveFolderFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorGetRemoteArchiveItemFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorExportRemoteArchiveItemsFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorArchiveMailboxServiceDiscoveryFailed,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotAttachSelf,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotDisableMandatoryExtension,
		[ODataHttpStatusCode(HttpStatusCode.NotFound)]
		ErrorExtensionNotFound,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCannotGetExternalEcpUrl,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorSearchQueryHasTooManyKeywords,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorSearchTooManyMailboxes,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidRetentionTagNone,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorDiscoverySearchesDisabled,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMaximumDevicesReached,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorCalendarSeekToConditionNotSupported,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidAppApiVersionSupported,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorInvalidAppSchemaVersionSupported,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorOrganizationAccessBlocked,
		[ODataHttpStatusCode(HttpStatusCode.BadRequest)]
		ErrorInvalidLicense,
		[ODataHttpStatusCode(HttpStatusCode.InternalServerError)]
		ErrorMessagePerFolderCountReceiveQuotaExceeded
	}
}
