using System;
using System.Collections.Generic;
using System.Reflection;
using System.Security.AccessControl;

namespace Microsoft.Exchange.Data.Directory
{
	[Serializable]
	internal class ADPropertyDefinition : SimpleProviderPropertyDefinition
	{
		public string LdapDisplayName
		{
			get
			{
				return this.ldapDisplayName;
			}
		}

		public IFormatProvider FormatProvider
		{
			get
			{
				return this.formatProvider;
			}
		}

		public SimpleProviderPropertyDefinition MServPropertyDefinition
		{
			get
			{
				return this.mservPropertyDefinition;
			}
		}

		public SimpleProviderPropertyDefinition MbxPropertyDefinition
		{
			get
			{
				return this.mbxPropertyDefinition;
			}
		}

		public ADPropertyDefinition ShadowProperty
		{
			get
			{
				return this.shadowProperty;
			}
		}

		public ADPropertyDefinition SoftLinkShadowProperty
		{
			get
			{
				return this.softLinkShadowProperty;
			}
		}

		public new ADPropertyDefinitionFlags Flags
		{
			get
			{
				return (ADPropertyDefinitionFlags)base.Flags;
			}
		}

		public bool IncludeInProvisionalClone
		{
			get
			{
				return (this.Flags & ADPropertyDefinitionFlags.DoNotProvisionalClone) == ADPropertyDefinitionFlags.None;
			}
		}

		public bool IsSoftLinkAttribute
		{
			get
			{
				return this.softLinkShadowProperty != null;
			}
		}

		public bool IsValidateInFirstOrganization
		{
			get
			{
				return (this.Flags & ADPropertyDefinitionFlags.ValidateInFirstOrganization) != ADPropertyDefinitionFlags.None;
			}
		}

		public bool IsDoNotValidate
		{
			get
			{
				return (this.Flags & ADPropertyDefinitionFlags.DoNotValidate) != ADPropertyDefinitionFlags.None;
			}
		}

		public bool IsBackLink
		{
			get
			{
				return (this.Flags & ADPropertyDefinitionFlags.BackLink) != ADPropertyDefinitionFlags.None;
			}
		}

		public bool IsRanged
		{
			get
			{
				return (this.Flags & ADPropertyDefinitionFlags.Ranged) != ADPropertyDefinitionFlags.None;
			}
		}

		public bool IsValidateInSameOrganization
		{
			get
			{
				return base.Type == typeof(ADObjectId) && !this.IsValidateInFirstOrganization && !this.IsDoNotValidate && !this.IsBackLink;
			}
		}

		public bool IsValidateInSharedConfig
		{
			get
			{
				return (this.Flags & ADPropertyDefinitionFlags.ValidateInSharedConfig) != ADPropertyDefinitionFlags.None;
			}
		}

		public bool IsNonADProperty
		{
			get
			{
				return (this.Flags & ADPropertyDefinitionFlags.NonADProperty) != ADPropertyDefinitionFlags.None;
			}
		}

		internal static bool CanHaveAutogeneratedConstraints(ADPropertyDefinition propertyDefinition)
		{
			return propertyDefinition != null && (!propertyDefinition.IsNonADProperty && !propertyDefinition.HasAutogeneratedConstraints && !propertyDefinition.IsFilterOnly && !propertyDefinition.IsCalculated && !propertyDefinition.IsReadOnly && !propertyDefinition.IsTaskPopulated) && !string.IsNullOrEmpty(propertyDefinition.LdapDisplayName);
		}

		internal ADPropertyDefinition(string name, ExchangeObjectVersion versionAdded, Type type, IFormatProvider formatProvider, string ldapDisplayName, string shadowLdapDisplayName, ADPropertyDefinitionFlags flags, object defaultValue, PropertyDefinitionConstraint[] readConstraints, PropertyDefinitionConstraint[] writeConstraints, ProviderPropertyDefinition[] supportingProperties, CustomFilterBuilderDelegate customFilterBuilderDelegate, GetterDelegate getterDelegate, SetterDelegate setterDelegate, SimpleProviderPropertyDefinition mservPropertyDefinition = null, SimpleProviderPropertyDefinition mbxPropertyDefinition = null) : this(name, versionAdded, type, formatProvider, ldapDisplayName, shadowLdapDisplayName, null, flags, defaultValue, readConstraints, writeConstraints, supportingProperties, customFilterBuilderDelegate, getterDelegate, setterDelegate, mservPropertyDefinition, mbxPropertyDefinition)
		{
		}

		internal ADPropertyDefinition(string name, ExchangeObjectVersion versionAdded, Type type, IFormatProvider formatProvider, string ldapDisplayName, string shadowLdapDisplayName, string softLinkLdapDisplayName, ADPropertyDefinitionFlags flags, object defaultValue, PropertyDefinitionConstraint[] readConstraints, PropertyDefinitionConstraint[] writeConstraints, ProviderPropertyDefinition[] supportingProperties, CustomFilterBuilderDelegate customFilterBuilderDelegate, GetterDelegate getterDelegate, SetterDelegate setterDelegate, SimpleProviderPropertyDefinition mservPropertyDefinition = null, SimpleProviderPropertyDefinition mbxPropertyDefinition = null) : base(name, versionAdded, type, (PropertyDefinitionFlags)flags, defaultValue, readConstraints, writeConstraints, supportingProperties, customFilterBuilderDelegate, getterDelegate, setterDelegate)
		{
			this.formatProvider = formatProvider;
			this.ldapDisplayName = ldapDisplayName;
			this.mservPropertyDefinition = mservPropertyDefinition;
			this.mbxPropertyDefinition = mbxPropertyDefinition;
			if (string.IsNullOrEmpty(this.LdapDisplayName))
			{
				if (!this.IsCalculated && !this.IsTaskPopulated && !this.IsNonADProperty)
				{
					throw new ArgumentException(base.Name + ": Non-calculated properties must have LdapDisplayName", "ldapDisplayName");
				}
			}
			else
			{
				if (this.IsCalculated && base.CustomFilterBuilderDelegate != new CustomFilterBuilderDelegate(ADObject.DummyCustomFilterBuilderDelegate))
				{
					throw new ArgumentException(base.Name + ": Calculated properties should not contain an LdapDisplayName, unless it is the DummyCustomFilterBuilderDelegate.", "ldapDisplayName");
				}
				if (this.IsTaskPopulated)
				{
					throw new ArgumentException(base.Name + ": TaskPopulated properties should not contain an LdapDisplayName.", "ldapDisplayName");
				}
			}
			if (!this.IsMultivalued && !this.IsFilterOnly && !this.IsCalculated && !this.IsMandatory && base.Type == typeof(string) && !string.Empty.Equals(base.DefaultValue))
			{
				throw new ArgumentException(base.Name + ": Non-mandatory string properties must have default value String.Empty. Found " + (base.DefaultValue ?? "<null>"), "defaultValue");
			}
			if (this.IsValidateInFirstOrganization || this.IsDoNotValidate || this.IsBackLink)
			{
				if ((this.IsValidateInFirstOrganization && this.IsDoNotValidate) || (this.IsDoNotValidate && this.IsBackLink) || (this.IsValidateInFirstOrganization && this.IsBackLink))
				{
					throw new ArgumentException(base.Name + ": Only one of the three property definition flags - ValidateInFirstOrganization, DoNotValidate and BackLink can be set in parameter flags");
				}
				if (base.Type != typeof(ADObjectId))
				{
					throw new ArgumentException(base.Name + ": If ValidateInFirstOrganization, DoNotValidate or BackLink is set for parameter flags, the property type MUST be ADObjectId");
				}
			}
			if (this.IsRanged && (!this.IsMultivalued || string.IsNullOrEmpty(this.ldapDisplayName) || !this.IsReadOnly))
			{
				throw new ArgumentException(base.Name + ": Only multivalued non calculated properties can be ranged.");
			}
			if (!string.IsNullOrEmpty(this.ldapDisplayName) && this.IsRanged != this.ldapDisplayName.ToLower().Contains(";range="))
			{
				throw new ArgumentException(base.Name + ": Ranged property needs to define range in ldapName.");
			}
			if (!string.IsNullOrEmpty(shadowLdapDisplayName))
			{
				if (this.IsCalculated || this.IsReadOnly || this.IsFilterOnly || this.IsTaskPopulated || this.IsSoftLinkAttribute)
				{
					throw new ArgumentException(base.Name + ": Calculated, ReadOnly, FilterOnly, SoftLink, or TaskPopulated properties may not have shadows");
				}
				Type type2;
				ADPropertyDefinitionFlags flags2;
				object defaultValue2;
				if (type.GetTypeInfo().IsValueType && (flags & ADPropertyDefinitionFlags.PersistDefaultValue) == ADPropertyDefinitionFlags.PersistDefaultValue)
				{
					Type typeFromHandle = typeof(Nullable<>);
					type2 = typeFromHandle.MakeGenericType(new Type[]
					{
						type
					});
					flags2 = (flags & ~ADPropertyDefinitionFlags.PersistDefaultValue);
					defaultValue2 = null;
				}
				else
				{
					type2 = type;
					flags2 = flags;
					defaultValue2 = defaultValue;
				}
				this.shadowProperty = new ADPropertyDefinition(string.Format("Shadow{0}", name), ExchangeObjectVersion.Exchange2003, type2, formatProvider, shadowLdapDisplayName, null, null, flags2, defaultValue2, PropertyDefinitionConstraint.None, PropertyDefinitionConstraint.None, SimpleProviderPropertyDefinition.None, null, null, null, null, null);
			}
			if (!string.IsNullOrEmpty(softLinkLdapDisplayName))
			{
				if (this.IsCalculated || this.IsReadOnly || this.IsFilterOnly || this.IsTaskPopulated)
				{
					throw new ArgumentException(base.Name + ": Calculated, ReadOnly, FilterOnly, or TaskPopulated properties may not have soft links");
				}
				Type typeFromHandle2 = typeof(byte[]);
				ADPropertyDefinitionFlags flags3 = ADPropertyDefinitionFlags.Binary;
				this.softLinkShadowProperty = new ADPropertyDefinition(string.Format("{0}_sl", name), ExchangeObjectVersion.Exchange2003, typeFromHandle2, formatProvider, softLinkLdapDisplayName, null, null, flags3, null, PropertyDefinitionConstraint.None, PropertyDefinitionConstraint.None, SimpleProviderPropertyDefinition.None, null, null, null, null, null);
			}
		}

		internal ADPropertyDefinition(string name, ExchangeObjectVersion versionAdded, Type type, IFormatProvider formatProvider, string ldapDisplayName, ADPropertyDefinitionFlags flags, object defaultValue, PropertyDefinitionConstraint[] readConstraints, PropertyDefinitionConstraint[] writeConstraints, ProviderPropertyDefinition[] supportingProperties, CustomFilterBuilderDelegate customFilterBuilderDelegate, GetterDelegate getterDelegate, SetterDelegate setterDelegate, SimpleProviderPropertyDefinition mservPropertyDefinition = null, SimpleProviderPropertyDefinition mbxPropertyDefinition = null) : this(name, versionAdded, type, formatProvider, ldapDisplayName, null, null, flags, defaultValue, readConstraints, writeConstraints, supportingProperties, customFilterBuilderDelegate, getterDelegate, setterDelegate, mservPropertyDefinition, mbxPropertyDefinition)
		{
		}

		internal ADPropertyDefinition(string name, ExchangeObjectVersion versionAdded, Type type, string ldapDisplayName, string shadowLdapDisplayName, ADPropertyDefinitionFlags flags, object defaultValue, PropertyDefinitionConstraint[] readConstraints, PropertyDefinitionConstraint[] writeConstraints, ProviderPropertyDefinition[] supportingProperties, CustomFilterBuilderDelegate customFilterBuilderDelegate, GetterDelegate getterDelegate, SetterDelegate setterDelegate, SimpleProviderPropertyDefinition mservPropertyDefinition = null, SimpleProviderPropertyDefinition mbxPropertyDefinition = null) : this(name, versionAdded, type, null, ldapDisplayName, shadowLdapDisplayName, flags, defaultValue, readConstraints, writeConstraints, supportingProperties, customFilterBuilderDelegate, getterDelegate, setterDelegate, mservPropertyDefinition, mbxPropertyDefinition)
		{
		}

		internal ADPropertyDefinition(string name, ExchangeObjectVersion versionAdded, Type type, string ldapDisplayName, ADPropertyDefinitionFlags flags, object defaultValue, PropertyDefinitionConstraint[] readConstraints, PropertyDefinitionConstraint[] writeConstraints, ProviderPropertyDefinition[] supportingProperties, CustomFilterBuilderDelegate customFilterBuilderDelegate, GetterDelegate getterDelegate, SetterDelegate setterDelegate, SimpleProviderPropertyDefinition mservPropertyDefinition = null, SimpleProviderPropertyDefinition mbxPropertyDefinition = null) : this(name, versionAdded, type, null, ldapDisplayName, null, flags, defaultValue, readConstraints, writeConstraints, supportingProperties, customFilterBuilderDelegate, getterDelegate, setterDelegate, mservPropertyDefinition, mbxPropertyDefinition)
		{
		}

		public ADPropertyDefinition(string name, string shadowName, ExchangeObjectVersion versionAdded, Type type, IFormatProvider formatProvider, string ldapDisplayName, string shadowLdapDisplayName, ADPropertyDefinitionFlags flags, object defaultValue, PropertyDefinitionConstraint[] readConstraints, PropertyDefinitionConstraint[] writeConstraints, SimpleProviderPropertyDefinition mservPropertyDefinition = null, SimpleProviderPropertyDefinition mbxPropertyDefinition = null) : this(name, versionAdded, type, formatProvider, ldapDisplayName, shadowLdapDisplayName, flags, defaultValue, readConstraints, writeConstraints, SimpleProviderPropertyDefinition.None, null, null, null, mservPropertyDefinition, mbxPropertyDefinition)
		{
		}

		public ADPropertyDefinition(string name, ExchangeObjectVersion versionAdded, Type type, IFormatProvider formatProvider, string ldapDisplayName, ADPropertyDefinitionFlags flags, object defaultValue, PropertyDefinitionConstraint[] readConstraints, PropertyDefinitionConstraint[] writeConstraints, SimpleProviderPropertyDefinition mservPropertyDefinition = null, SimpleProviderPropertyDefinition mbxPropertyDefinition = null) : this(name, versionAdded, type, formatProvider, ldapDisplayName, null, flags, defaultValue, readConstraints, writeConstraints, SimpleProviderPropertyDefinition.None, null, null, null, mservPropertyDefinition, mbxPropertyDefinition)
		{
		}

		public ADPropertyDefinition(string name, string shadowName, ExchangeObjectVersion versionAdded, Type type, string ldapDisplayName, string shadowLdapDisplayName, ADPropertyDefinitionFlags flags, object defaultValue, PropertyDefinitionConstraint[] readConstraints, PropertyDefinitionConstraint[] writeConstraints, SimpleProviderPropertyDefinition mservPropertyDefinition = null, SimpleProviderPropertyDefinition mbxPropertyDefinition = null) : this(name, versionAdded, type, null, ldapDisplayName, shadowLdapDisplayName, flags, defaultValue, readConstraints, writeConstraints, SimpleProviderPropertyDefinition.None, null, null, null, mservPropertyDefinition, mbxPropertyDefinition)
		{
		}

		public ADPropertyDefinition(string name, ExchangeObjectVersion versionAdded, Type type, string ldapDisplayName, ADPropertyDefinitionFlags flags, object defaultValue, PropertyDefinitionConstraint[] readConstraints, PropertyDefinitionConstraint[] writeConstraints, SimpleProviderPropertyDefinition mservPropertyDefinition = null, SimpleProviderPropertyDefinition mbxPropertyDefinition = null) : this(name, versionAdded, type, null, ldapDisplayName, null, flags, defaultValue, readConstraints, writeConstraints, SimpleProviderPropertyDefinition.None, null, null, null, mservPropertyDefinition, mbxPropertyDefinition)
		{
		}

		public override bool Equals(ProviderPropertyDefinition other)
		{
			if (object.ReferenceEquals(other, this))
			{
				return true;
			}
			ADPropertyDefinition adpropertyDefinition = other as ADPropertyDefinition;
			return adpropertyDefinition != null && StringComparer.OrdinalIgnoreCase.Equals(adpropertyDefinition.LdapDisplayName, this.LdapDisplayName) && base.Equals(other);
		}

		public override int GetHashCode()
		{
			if (this.hashcode == 0)
			{
				int num = base.Name.GetHashCodeCaseInsensitive();
				if (string.Compare(base.Name, this.ldapDisplayName, StringComparison.OrdinalIgnoreCase) != 0)
				{
					num ^= ((this.ldapDisplayName == null) ? 0 : this.ldapDisplayName.GetHashCodeCaseInsensitive());
				}
				this.hashcode = num;
			}
			return this.hashcode;
		}

		public override bool IsFilterable
		{
			get
			{
				return (this.IsCalculated || !string.IsNullOrEmpty(this.LdapDisplayName)) && base.IsFilterable;
			}
		}

		public bool IsForestSpecific
		{
			get
			{
				return !this.IsSoftLinkAttribute && ((base.Type == typeof(ADObjectId) && this != ADObjectSchema.Id) || base.Type == typeof(ADObjectIdWithString) || base.Type == typeof(RawSecurityDescriptor) || base.Type == typeof(DNWithBinary) || (this.Flags & ADPropertyDefinitionFlags.ForestSpecific) != ADPropertyDefinitionFlags.None);
			}
		}

		public static GetterDelegate RawStringGetterIgnoringInvalid<TConverted>(ADPropertyDefinition rawPropertyDefinition, ADPropertyDefinition convertedPropertyDefinition)
		{
			if (!rawPropertyDefinition.IsMultivalued)
			{
				throw new NotImplementedException("RawStringGetterIgnoringInvalid is only currently implemented for multi-valued properties.");
			}
			return delegate(IPropertyBag bag)
			{
				MultiValuedProperty<string> multiValuedProperty = (MultiValuedProperty<string>)bag[rawPropertyDefinition];
				MultiValuedProperty<TConverted> result = null;
				List<TConverted> list = new List<TConverted>();
				bool flag = false;
				foreach (string originalValue in multiValuedProperty)
				{
					object obj;
					Exception ex;
					if (ADValueConvertor.TryConvertValueFromString(originalValue, typeof(TConverted), rawPropertyDefinition.FormatProvider, out obj, out ex))
					{
						list.Add((TConverted)((object)obj));
					}
					else
					{
						flag = true;
					}
				}
				if (!flag && list.Count != 0)
				{
					result = new MultiValuedProperty<TConverted>(rawPropertyDefinition.IsReadOnly, convertedPropertyDefinition, list);
				}
				return result;
			};
		}

		public static SetterDelegate RawStringSetter<TConverted>(ADPropertyDefinition rawPropertyDefinition)
		{
			if (!rawPropertyDefinition.IsMultivalued)
			{
				throw new NotImplementedException("RawStringSetter is only currently implemented for multi-valued properties.");
			}
			return delegate(object value, IPropertyBag bag)
			{
				MultiValuedProperty<TConverted> multiValuedProperty = (MultiValuedProperty<TConverted>)value;
				MultiValuedProperty<string> multiValuedProperty2 = null;
				if (multiValuedProperty != null && multiValuedProperty.Count != 0)
				{
					multiValuedProperty2 = new MultiValuedProperty<string>();
					foreach (TConverted tconverted in multiValuedProperty)
					{
						multiValuedProperty2.Add(ADValueConvertor.ConvertValueToString(tconverted, rawPropertyDefinition.FormatProvider));
					}
				}
				bag[rawPropertyDefinition] = multiValuedProperty2;
			};
		}

		private string ldapDisplayName;

		private IFormatProvider formatProvider;

		protected ADPropertyDefinition shadowProperty;

		protected ADPropertyDefinition softLinkShadowProperty;

		private SimpleProviderPropertyDefinition mservPropertyDefinition;

		private SimpleProviderPropertyDefinition mbxPropertyDefinition;
	}
}
