using System;

namespace Microsoft.Isam.Esent.Interop
{
	public enum JET_wrn
	{
		Success,
		RemainingVersions = 321,
		UniqueKey = 345,
		SeparateLongValue = 406,
		ExistingLogFileHasBadSignature = 558,
		ExistingLogFileIsNotContiguous,
		SkipThisRecord = 564,
		TargetInstanceRunning = 578,
		CommittedLogFilesLost = 585,
		CommittedLogFilesRemoved = 587,
		FinishWithUndo,
		DatabaseRepaired = 595,
		ColumnNull = 1004,
		BufferTruncated = 1006,
		DatabaseAttached,
		SortOverflow = 1009,
		SeekNotEqual = 1039,
		NoErrorInfo = 1055,
		NoIdleActivity = 1058,
		NoWriteLock = 1067,
		ColumnSetNull,
		ShrinkNotPossible = 1122,
		DTCCommitTransaction = 1163,
		DTCRollbackTransaction,
		TableEmpty = 1301,
		TableInUseBySystem = 1327,
		CorruptIndexDeleted = 1415,
		PrimaryIndexOutOfDate = 1417,
		SecondaryIndexOutOfDate,
		ColumnMaxTruncated = 1512,
		CopyLongValue = 1520,
		TaggedColumnsRemaining = 1523,
		ColumnSkipped = 1531,
		ColumnNotLocal,
		ColumnMoreTags,
		ColumnTruncated,
		ColumnPresent,
		ColumnSingleValue,
		ColumnDefault,
		ColumnNotInRecord = 1539,
		DataHasChanged = 1610,
		KeyChanged = 1618,
		FileOpenReadOnly = 1813,
		IdleFull = 1908,
		DefragAlreadyRunning = 2000,
		DefragNotRunning,
		DatabaseScanAlreadyRunning,
		DatabaseScanNotRunning,
		CallbackNotRegistered = 2100,
		PreviousLogFileIncomplete = 2602
	}
}
