using System;

namespace Microsoft.Exchange.Security
{
	internal enum SecurityStatus
	{
		OK,
		ContinueNeeded = 590610,
		CompleteNeeded,
		CompAndContinue,
		ContextExpired = 590615,
		CredentialsNeeded = 590624,
		Renegotiate,
		OutOfMemory = -2146893056,
		InvalidHandle,
		Unsupported,
		TargetUnknown,
		InternalError,
		PackageNotFound,
		NotOwner,
		CannotInstall,
		InvalidToken,
		CannotPack,
		QopNotSupported,
		NoImpersonation,
		LogonDenied,
		UnknownCredentials,
		NoCredentials,
		MessageAltered,
		OutOfSequence,
		NoAuthenticatingAuthority,
		IncompleteMessage = -2146893032,
		IncompleteCredentials = -2146893024,
		BufferNotEnough,
		WrongPrincipal,
		TimeSkew = -2146893020,
		UntrustedRoot,
		IllegalMessage,
		CertUnknown,
		CertExpired,
		EncryptFailure,
		DecryptFailure = -2146893008,
		AlgorithmMismatch,
		SecurityQosFailed,
		SmartcardLogonRequired = -2146892994,
		UnsupportedPreauth = -2146892989,
		BadBindings = -2146892986,
		ErrorMask = -2147483648,
		TLS1_0NotSupported,
		UnexpectedExchangeAuthBlob = 1,
		ExtendedProtectionMissingSpn,
		ExtendedProtectionWrongSpn,
		ExtendedProtectionOSNotPatched
	}
}
