using System;

namespace Microsoft.Exchange.AirSync
{
	public enum TimeId
	{
		[TimeId("Root")]
		Root,
		[TimeId("H_BPR")]
		HandlerBeginProcessRequest,
		[TimeId("H_PLC")]
		HandlerProxyLoginCommand,
		[TimeId("H_PR")]
		HandlerProxyRequest,
		[TimeId("H_SR")]
		HandlerScheduleTask,
		[TimeId("H_EPR")]
		HandlerEndProcessRequest,
		[TimeId("H_IRD")]
		HandlerIISRecordData,
		[TimeId("H_RMBP")]
		HandlerRequestMustBeProxied,
		[TimeId("H_CHRC")]
		HandlerCompleteHttpRequestCallback,
		[TimeId("H_SndW")]
		HandlerSendWatson,
		[TimeId("H_CRWD")]
		HandlerCompleteRequestWithDelay,
		[TimeId("H_HPL")]
		HandlerHandleProxyLogin,
		[TimeId("H_RMBP")]
		HandlerRequestsMustBeProxied,
		[TimeId("H_SDLE")]
		HandlerServiceDiscoveryLookupExternal,
		[TimeId("H_SDLI")]
		HandlerServiceDiscoveryLookupInternal,
		[TimeId("C_VXML")]
		CommandValidateXML,
		[TimeId("SM_VXML")]
		SendMailValidateXML,
		[TimeId("V_VXML")]
		ValidatorValidateXML,
		[TimeId("V_VXMLN")]
		ValidatorValidateXMLNode,
		[TimeId("V_VCSS")]
		ValidatorCreateSchemaSet,
		[TimeId("V_VCSSP")]
		ValidatorCreateSchemaSetParam,
		[TimeId("S_EC")]
		SettingsExecuteCommand,
		[TimeId("S_GVEX")]
		SettingsGetValidationErrorXml,
		[TimeId("S_RXR")]
		SettingsReadXmlRequest,
		[TimeId("S_IRX")]
		SettingsInitializeResponseXmlDocument,
		[TimeId("S_FRX")]
		SettingsFinalizeResponseXmlDocument,
		[TimeId("UIS_E")]
		UserInformationSettingsExecute,
		[TimeId("UIS_PG")]
		UserInformationSettingsProcessGet,
		[TimeId("RMS_E")]
		RMSExecute,
		[TimeId("RMS_PG")]
		RMSProcessGet,
		[TimeId("RMS_PE")]
		RMSProcessException,
		[TimeId("OOF_E")]
		OOFSettingsExecute,
		[TimeId("OOF_PG")]
		OOFSettingsProcessGet,
		[TimeId("OOF_PS")]
		OOFSettingsProcessSet,
		[TimeId("OOF_PE")]
		OOFSettingsProcessException,
		[TimeId("OOF_TTH")]
		OOFSettingsTextToHtml,
		[TimeId("OOF_HTT")]
		OOFSettingsHtmlToText,
		[TimeId("DI_E")]
		DeviceInfoExecute,
		[TimeId("DI_PS")]
		DeviceInfoProcessSet,
		[TimeId("DI_PE")]
		DeviceInfoProcessException,
		[TimeId("DP_E")]
		DevicePasswordExecute,
		[TimeId("DP_PS")]
		DevicePasswordProcessSet,
		[TimeId("TZ_E")]
		TimeZoneOffsetSettingsExecute,
		[TimeId("TZ_GET")]
		TimeZoneOffsetSettingsGet
	}
}
