using System;

namespace System.Reflection
{
	[Flags]
	internal enum INVOCATION_FLAGS : uint
	{
		INVOCATION_FLAGS_UNKNOWN = 0U,
		INVOCATION_FLAGS_INITIALIZED = 1U,
		INVOCATION_FLAGS_NO_INVOKE = 2U,
		INVOCATION_FLAGS_NEED_SECURITY = 4U,
		INVOCATION_FLAGS_NO_CTOR_INVOKE = 8U,
		INVOCATION_FLAGS_IS_CTOR = 16U,
		INVOCATION_FLAGS_RISKY_METHOD = 32U,
		INVOCATION_FLAGS_NON_W8P_FX_API = 64U,
		INVOCATION_FLAGS_IS_DELEGATE_CTOR = 128U,
		INVOCATION_FLAGS_CONTAINS_STACK_POINTERS = 256U,
		INVOCATION_FLAGS_SPECIAL_FIELD = 16U,
		INVOCATION_FLAGS_FIELD_SPECIAL_CAST = 32U,
		INVOCATION_FLAGS_CONSTRUCTOR_INVOKE = 268435456U
	}
}
