using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Web.UI;

[assembly: AssemblyVersion("15.0.0.0")]
[assembly: WebResource("NewPublicFolders.js", "text/javascript")]
[assembly: ScriptResource("NewPublicFolders.js", "Microsoft.Exchange.Management.ControlPanel.NewPublicFolders", "NewPublicFolders")]
[assembly: WebResource("EditPublicFolderMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditPublicFolders.js", "Microsoft.Exchange.Management.ControlPanel.EditPublicFolders", "EditPublicFolders")]
[assembly: ScriptResource("EditPublicFolderMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditPublicFolderMailbox", "EditPublicFolderMailbox")]
[assembly: WebResource("NewPublicFolderMailbox.js", "text/javascript")]
[assembly: ScriptResource("NewPublicFolderMailbox.js", "Microsoft.Exchange.Management.ControlPanel.NewPublicFolderMailbox", "NewPublicFolderMailbox")]
[assembly: AssemblyFileVersion("15.00.1497.012")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("(C) 2014 Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyTrademark("Microsoft(R) is a registered trademark of Microsoft Corporation.")]
[assembly: AssemblyProduct("Microsoft(R) Exchange")]
[assembly: CLSCompliant(false)]
[assembly: ComVisible(false)]
[assembly: TagPrefix("Microsoft.Exchange.Management.ControlPanel.WebControls", "ecp")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Common.js", "application/x-javascript")]
[assembly: ScriptResource("Microsoft.Exchange.Management.ControlPanel.Client.Common.js", "Microsoft.Exchange.Management.ControlPanel.ClientStrings", "ImportedStrings")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Navigation.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.List.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.WizardProperties.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Wizard.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Pickers.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Calendar.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.OwaOptions.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.RegionalProperties.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Reporting.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Rules.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Connect.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Extension.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Voicemail.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.SMSProperties.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.PerformanceConsole.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.DeliveryReports.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.AuditReports.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.AutomaticReplies.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Messaging.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Users.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.UnifiedMessaging.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Mailbox.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.DeviceAccessRule.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.OrgSettings.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.DLPPolicy.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.MessageTrace.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Quarantine.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Antispam.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.Antimalware.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.ReportingFramework.js", "application/x-javascript")]
[assembly: WebResource("Microsoft.Exchange.Management.ControlPanel.Client.ExtendedReportRequest.js", "application/x-javascript")]
[assembly: InternalsVisibleTo("Microsoft.Exchange.Management.Reports.VisualizationFramework.Extensions,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Microsoft.Office.Compliance.Console,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Microsoft.Office.Compliance.Console.Extensions,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Microsoft.Exchange.Quarantine.Console,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Management.ControlPanel.ZeroBoxTests,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Admin.ControlPanel.Common,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Admin.ControlPanel.Infrastructure,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Admin.ControlPanel.Common.SingleBox,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Admin.ControlPanel.Generic,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Admin.ControlPanel.WebService,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Admin.ControlPanel.P0TestCases,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Admin.UMC.P0TestCases,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Admin.UMC.TestPage,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Admin.UMC.UnitTest.Service,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Management,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Internal.Exchange.Hygiene.Test.CustomerSettings,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Microsoft.Exchange.Management.ControlPanel.Eds,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Microsoft.Exchange.Management.ControlPanel.Osp,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Microsoft.Exchange.Management.ControlPanel.Osi.Common,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("Microsoft.Exchange.Management.ControlPanel.Osi,PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: ContractNamespace("ECP", ClrNamespace = "Microsoft.Exchange.Management.ControlPanel")]
[assembly: ContractNamespace("ECP", ClrNamespace = "Microsoft.Exchange.Management.DDIService")]
[assembly: WebResource("ADAttribute.js", "text/javascript")]
[assembly: ScriptResource("ADAttribute.js", "Microsoft.Exchange.Management.ControlPanel.ADAttribute", "ADAttribute")]
[assembly: WebResource("AddDatabaseCopyFVA.js", "text/javascript")]
[assembly: ScriptResource("AddDatabaseCopyFVA.js", "Microsoft.Exchange.Management.ControlPanel.AddDatabaseCopyFVA", "AddDatabaseCopyFVA")]
[assembly: WebResource("AddProxyEmailAddress.js", "text/javascript")]
[assembly: ScriptResource("AddProxyEmailAddress.js", "Microsoft.Exchange.Management.ControlPanel.AddProxyEmailAddress", "AddProxyEmailAddress")]
[assembly: WebResource("AddressTemplatePopupFormFVA.js", "text/javascript")]
[assembly: ScriptResource("AddressTemplatePopupFormFVA.js", "Microsoft.Exchange.Management.ControlPanel.AddressTemplatePopupFormFVA", "AddressTemplatePopupFormFVA")]
[assembly: WebResource("AddUMExtension.js", "text/javascript")]
[assembly: ScriptResource("AddUMExtension.js", "Microsoft.Exchange.Management.ControlPanel.AddUMExtension", "AddUMExtension")]
[assembly: WebResource("AllowIPAddressFVA.js", "text/javascript")]
[assembly: ScriptResource("AllowIPAddressFVA.js", "Microsoft.Exchange.Management.ControlPanel.AllowIPAddressFVA", "AllowIPAddressFVA")]
[assembly: WebResource("AuditLogReportFVA.js", "text/javascript")]
[assembly: ScriptResource("AuditLogReportFVA.js", "Microsoft.Exchange.Management.ControlPanel.AuditLogReportFVA", "AuditLogReportFVA")]
[assembly: WebResource("AuditReportsFVA.js", "text/javascript")]
[assembly: ScriptResource("AuditReportsFVA.js", "Microsoft.Exchange.Management.ControlPanel.AuditReportsFVA", "AuditReportsFVA")]
[assembly: WebResource("BlockIPAddressFVA.js", "text/javascript")]
[assembly: ScriptResource("BlockIPAddressFVA.js", "Microsoft.Exchange.Management.ControlPanel.BlockIPAddressFVA", "BlockIPAddressFVA")]
[assembly: WebResource("BulkEditMailbox.js", "text/javascript")]
[assembly: ScriptResource("BulkEditMailbox.js", "Microsoft.Exchange.Management.ControlPanel.BulkEditMailbox", "BulkEditMailbox")]
[assembly: WebResource("NewCertificate.js", "text/javascript")]
[assembly: ScriptResource("NewCertificate.js", "Microsoft.Exchange.Management.ControlPanel.NewCertificate", "NewCertificate")]
[assembly: WebResource("CompleteCertificate.js", "text/javascript")]
[assembly: ScriptResource("CompleteCertificate.js", "Microsoft.Exchange.Management.ControlPanel.CompleteCertificate", "CompleteCertificate")]
[assembly: WebResource("RenewCertificate.js", "text/javascript")]
[assembly: ScriptResource("RenewCertificate.js", "Microsoft.Exchange.Management.ControlPanel.RenewCertificate", "RenewCertificate")]
[assembly: WebResource("ImportCertificate.js", "text/javascript")]
[assembly: ScriptResource("ImportCertificate.js", "Microsoft.Exchange.Management.ControlPanel.ImportCertificate", "ImportCertificate")]
[assembly: WebResource("ExportCertificate.js", "text/javascript")]
[assembly: ScriptResource("ExportCertificate.js", "Microsoft.Exchange.Management.ControlPanel.ExportCertificate", "ExportCertificate")]
[assembly: WebResource("EditCertificate.js", "text/javascript")]
[assembly: ScriptResource("EditCertificate.js", "Microsoft.Exchange.Management.ControlPanel.EditCertificate", "EditCertificate")]
[assembly: WebResource("EditReceiveConnector.js", "text/javascript")]
[assembly: ScriptResource("EditReceiveConnector.js", "Microsoft.Exchange.Management.ControlPanel.EditReceiveConnector", "EditReceiveConnector")]
[assembly: WebResource("NewReceiveConnector.js", "text/javascript")]
[assembly: ScriptResource("NewReceiveConnector.js", "Microsoft.Exchange.Management.ControlPanel.NewReceiveConnector", "NewReceiveConnector")]
[assembly: WebResource("NewSendConnector.js", "text/javascript")]
[assembly: ScriptResource("NewSendConnector.js", "Microsoft.Exchange.Management.ControlPanel.NewSendConnector", "NewSendConnector")]
[assembly: WebResource("EditSendConnector.js", "text/javascript")]
[assembly: ScriptResource("EditSendConnector.js", "Microsoft.Exchange.Management.ControlPanel.EditSendConnector", "EditSendConnector")]
[assembly: WebResource("AddressSpaceEntry.js", "text/javascript")]
[assembly: ScriptResource("AddressSpaceEntry.js", "Microsoft.Exchange.Management.ControlPanel.AddressSpaceEntry", "AddressSpaceEntry")]
[assembly: WebResource("IPBindingEntry.js", "text/javascript")]
[assembly: ScriptResource("IPBindingEntry.js", "Microsoft.Exchange.Management.ControlPanel.IPBindingEntry", "IPBindingEntry")]
[assembly: WebResource("DomainEditor.js", "text/javascript")]
[assembly: ScriptResource("DomainEditor.js", "Microsoft.Exchange.Management.ControlPanel.DomainEditor", "DomainEditor")]
[assembly: WebResource("CalendarPublishingFVA.js", "text/javascript")]
[assembly: ScriptResource("CalendarPublishingFVA.js", "Microsoft.Exchange.Management.ControlPanel.CalendarPublishingFVA", "CalendarPublishingFVA")]
[assembly: WebResource("ConnectFVA.js", "text/javascript")]
[assembly: ScriptResource("ConnectFVA.js", "Microsoft.Exchange.Management.ControlPanel.ConnectFVA", "ConnectFVA")]
[assembly: WebResource("ConnectMailboxWizardFVA.js", "text/javascript")]
[assembly: ScriptResource("ConnectMailboxWizardFVA.js", "Microsoft.Exchange.Management.ControlPanel.ConnectMailboxWizardFVA", "ConnectMailboxWizardFVA")]
[assembly: WebResource("DAG.js", "text/javascript")]
[assembly: ScriptResource("DAG.js", "Microsoft.Exchange.Management.ControlPanel.DAG", "DAG")]
[assembly: WebResource("DAGNetworkFVA.js", "text/javascript")]
[assembly: ScriptResource("DAGNetworkFVA.js", "Microsoft.Exchange.Management.ControlPanel.DAGNetworkFVA", "DAGNetworkFVA")]
[assembly: WebResource("Databases.js", "text/javascript")]
[assembly: ScriptResource("Databases.js", "Microsoft.Exchange.Management.ControlPanel.Databases", "Databases")]
[assembly: WebResource("DomainEntryFVA.js", "text/javascript")]
[assembly: ScriptResource("DomainEntryFVA.js", "Microsoft.Exchange.Management.ControlPanel.DomainEntryFVA", "DomainEntryFVA")]
[assembly: WebResource("EditAcceptedDomain.js", "text/javascript")]
[assembly: ScriptResource("EditAcceptedDomain.js", "Microsoft.Exchange.Management.ControlPanel.EditAcceptedDomain", "EditAcceptedDomain")]
[assembly: WebResource("EditAccount.js", "text/javascript")]
[assembly: ScriptResource("EditAccount.js", "Microsoft.Exchange.Management.ControlPanel.EditAccount", "EditAccount")]
[assembly: WebResource("EditActiveSyncMailboxPolicy.js", "text/javascript")]
[assembly: ScriptResource("EditActiveSyncMailboxPolicy.js", "Microsoft.Exchange.Management.ControlPanel.EditActiveSyncMailboxPolicy", "EditActiveSyncMailboxPolicy")]
[assembly: WebResource("EditActiveSyncSettings.js", "text/javascript")]
[assembly: ScriptResource("EditActiveSyncSettings.js", "Microsoft.Exchange.Management.ControlPanel.EditActiveSyncSettings", "EditActiveSyncSettings")]
[assembly: WebResource("EditAddressListFVA.js", "text/javascript")]
[assembly: ScriptResource("EditAddressListFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditAddressListFVA", "EditAddressListFVA")]
[assembly: WebResource("EditAppFVA.js", "text/javascript")]
[assembly: ScriptResource("EditAppFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditAppFVA", "EditAppFVA")]
[assembly: WebResource("EditAntimalwarePolicyFVA.js", "text/javascript")]
[assembly: ScriptResource("EditAntimalwarePolicyFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditAntimalwarePolicyFVA", "EditAntimalwarePolicyFVA")]
[assembly: WebResource("EditAntispamPolicyFVA.js", "text/javascript")]
[assembly: ScriptResource("EditAntispamPolicyFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditAntispamPolicyFVA", "EditAntispamPolicyFVA")]
[assembly: WebResource("EditArchiveMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditArchiveMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditArchiveMailbox", "EditArchiveMailbox")]
[assembly: WebResource("EditDatabaseCopyFVA.js", "text/javascript")]
[assembly: ScriptResource("EditDatabaseCopyFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditDatabaseCopyFVA", "EditDatabaseCopyFVA")]
[assembly: WebResource("EditDataClassificationFVA.js", "text/javascript")]
[assembly: ScriptResource("EditDataClassificationFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditDataClassificationFVA", "EditDataClassificationFVA")]
[assembly: WebResource("EditDataClassificationLanguageFVA.js", "text/javascript")]
[assembly: ScriptResource("EditDataClassificationLanguageFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditDataClassificationLanguageFVA", "EditDataClassificationLanguageFVA")]
[assembly: WebResource("EditDeviceAccessRule.js", "text/javascript")]
[assembly: ScriptResource("EditDeviceAccessRule.js", "Microsoft.Exchange.Management.ControlPanel.EditDeviceAccessRule", "EditDeviceAccessRule")]
[assembly: WebResource("EditDiscoveryHold.js", "text/javascript")]
[assembly: ScriptResource("EditDiscoveryHold.js", "Microsoft.Exchange.Management.ControlPanel.EditDiscoveryHold", "EditDiscoveryHold")]
[assembly: WebResource("EditDistributionGroup.js", "text/javascript")]
[assembly: ScriptResource("EditDistributionGroup.js", "Microsoft.Exchange.Management.ControlPanel.EditDistributionGroup", "EditDistributionGroup")]
[assembly: WebResource("EditDLPPolicyFVA.js", "text/javascript")]
[assembly: ScriptResource("EditDLPPolicyFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditDLPPolicyFVA", "EditDLPPolicyFVA")]
[assembly: WebResource("EditDLPAttributeFVA.js", "text/javascript")]
[assembly: ScriptResource("EditDLPAttributeFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditDLPAttributeFVA", "EditDLPAttributeFVA")]
[assembly: WebResource("EditMobileMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditMobileMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditMobileMailbox", "EditMobileMailbox")]
[assembly: WebResource("EditEmailAddress.js", "text/javascript")]
[assembly: ScriptResource("EditEmailAddress.js", "Microsoft.Exchange.Management.ControlPanel.EditEmailAddress", "EditEmailAddress")]
[assembly: WebResource("EditEmailAddressPolicyFVA.js", "text/javascript")]
[assembly: ScriptResource("EditEmailAddressPolicyFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditEmailAddressPolicyFVA", "EditEmailAddressPolicyFVA")]
[assembly: WebResource("EditEnduserSpamNotificationFVA.js", "text/javascript")]
[assembly: ScriptResource("EditEnduserSpamNotificationFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditEnduserSpamNotificationFVA", "EditEnduserSpamNotificationFVA")]
[assembly: WebResource("EditEquipmentMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditEquipmentMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditEquipmentMailbox", "EditEquipmentMailbox")]
[assembly: WebResource("EditFFODistributionGroupFVA.js", "text/javascript")]
[assembly: ScriptResource("EditFFODistributionGroupFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditFFODistributionGroupFVA", "EditFFODistributionGroupFVA")]
[assembly: WebResource("EditFFOMailUserFVA.js", "text/javascript")]
[assembly: ScriptResource("EditFFOMailUserFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditFFOMailUserFVA", "EditFFOMailUserFVA")]
[assembly: WebResource("EditFFOUserAdvFilterFVA.js", "text/javascript")]
[assembly: ScriptResource("EditFFOUserAdvFilterFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditFFOUserAdvFilterFVA", "EditFFOUserAdvFilterFVA")]
[assembly: WebResource("EditGroupNamingPolicy.js", "text/javascript")]
[assembly: ScriptResource("EditGroupNamingPolicy.js", "Microsoft.Exchange.Management.ControlPanel.EditGroupNamingPolicy", "EditGroupNamingPolicy")]
[assembly: WebResource("EditHotmailSubscription.js", "text/javascript")]
[assembly: ScriptResource("EditHotmailSubscription.js", "Microsoft.Exchange.Management.ControlPanel.EditHotmailSubscription", "EditHotmailSubscription")]
[assembly: WebResource("EditImapSubscription.js", "text/javascript")]
[assembly: ScriptResource("EditImapSubscription.js", "Microsoft.Exchange.Management.ControlPanel.EditImapSubscription", "EditImapSubscription")]
[assembly: WebResource("EditInboundConnectorFVA.js", "text/javascript")]
[assembly: ScriptResource("EditInboundConnectorFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditInboundConnectorFVA", "EditInboundConnectorFVA")]
[assembly: WebResource("EditLinkedMailboxFVA.js", "text/javascript")]
[assembly: ScriptResource("EditLinkedMailboxFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditLinkedMailboxFVA", "EditLinkedMailboxFVA")]
[assembly: WebResource("EditLitigationHold.js", "text/javascript")]
[assembly: ScriptResource("EditLitigationHold.js", "Microsoft.Exchange.Management.ControlPanel.EditLitigationHold", "EditLitigationHold")]
[assembly: WebResource("EditMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditMailbox", "EditMailbox")]
[assembly: WebResource("EditMailboxSearch.js", "text/javascript")]
[assembly: ScriptResource("EditMailboxSearch.js", "Microsoft.Exchange.Management.ControlPanel.EditMailboxSearch", "EditMailboxSearch")]
[assembly: WebResource("EditMailContact.js", "text/javascript")]
[assembly: ScriptResource("EditMailContact.js", "Microsoft.Exchange.Management.ControlPanel.EditMailContact", "EditMailContact")]
[assembly: WebResource("EditMailRoutingDomain.js", "text/javascript")]
[assembly: ScriptResource("EditMailRoutingDomain.js", "Microsoft.Exchange.Management.ControlPanel.EditMailRoutingDomain", "EditMailRoutingDomain")]
[assembly: WebResource("EditMailUser.js", "text/javascript")]
[assembly: ScriptResource("EditMailUser.js", "Microsoft.Exchange.Management.ControlPanel.EditMailUser", "EditMailUser")]
[assembly: WebResource("EditMigrationBatch.js", "text/javascript")]
[assembly: ScriptResource("EditMigrationBatch.js", "Microsoft.Exchange.Management.ControlPanel.EditMigrationBatch", "EditMigrationBatch")]
[assembly: WebResource("EditMigrationEndpoint.js", "text/javascript")]
[assembly: ScriptResource("EditMigrationEndpoint.js", "Microsoft.Exchange.Management.ControlPanel.EditMigrationEndpoint", "EditMigrationEndpoint")]
[assembly: WebResource("EditMyDistributionGroup.js", "text/javascript")]
[assembly: ScriptResource("EditMyDistributionGroup.js", "Microsoft.Exchange.Management.ControlPanel.EditMyDistributionGroup", "EditMyDistributionGroup")]
[assembly: WebResource("EditOmsAccount.js", "text/javascript")]
[assembly: ScriptResource("EditOmsAccount.js", "Microsoft.Exchange.Management.ControlPanel.EditOmsAccount", "EditOmsAccount")]
[assembly: WebResource("EditOrganizationRelationshipFVA.js", "text/javascript")]
[assembly: ScriptResource("EditOrganizationRelationshipFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditOrganizationRelationshipFVA", "EditOrganizationRelationshipFVA")]
[assembly: WebResource("EditOutboundConnectorFVA.js", "text/javascript")]
[assembly: ScriptResource("EditOutboundConnectorFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditOutboundConnectorFVA", "EditOutboundConnectorFVA")]
[assembly: WebResource("EditOutlookSettingsFVA.js", "text/javascript")]
[assembly: ScriptResource("EditOutlookSettingsFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditOutlookSettingsFVA", "EditOutlookSettingsFVA")]
[assembly: WebResource("EditOwaMailboxPolicy.js", "text/javascript")]
[assembly: ScriptResource("EditOwaMailboxPolicy.js", "Microsoft.Exchange.Management.ControlPanel.EditOwaMailboxPolicy", "EditOwaMailboxPolicy")]
[assembly: WebResource("EditPopSubscription.js", "text/javascript")]
[assembly: ScriptResource("EditPopSubscription.js", "Microsoft.Exchange.Management.ControlPanel.EditPopSubscription", "EditPopSubscription")]
[assembly: WebResource("EditProxyEmailAddress.js", "text/javascript")]
[assembly: ScriptResource("EditProxyEmailAddress.js", "Microsoft.Exchange.Management.ControlPanel.EditProxyEmailAddress", "EditProxyEmailAddress")]
[assembly: WebResource("EditQuarantineAdvFilterFVA.js", "text/javascript")]
[assembly: ScriptResource("EditQuarantineAdvFilterFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditQuarantineAdvFilterFVA", "EditQuarantineAdvFilterFVA")]
[assembly: WebResource("EditRecipientAdvFilter.js", "text/javascript")]
[assembly: ScriptResource("EditRecipientAdvFilter.js", "Microsoft.Exchange.Management.ControlPanel.EditRecipientAdvFilter", "EditRecipientAdvFilter")]
[assembly: WebResource("EditRemoteMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditRemoteMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditRemoteMailbox", "EditRemoteMailbox")]
[assembly: WebResource("EditRetentionPolicy.js", "text/javascript")]
[assembly: ScriptResource("EditRetentionPolicy.js", "Microsoft.Exchange.Management.ControlPanel.EditRetentionPolicy", "EditRetentionPolicy")]
[assembly: WebResource("EditRetentionPolicyTag.js", "text/javascript")]
[assembly: ScriptResource("EditRetentionPolicyTag.js", "Microsoft.Exchange.Management.ControlPanel.EditRetentionPolicyTag", "EditRetentionPolicyTag")]
[assembly: WebResource("EditRoleAssignmentPolicy.js", "text/javascript")]
[assembly: ScriptResource("EditRoleAssignmentPolicy.js", "Microsoft.Exchange.Management.ControlPanel.EditRoleAssignmentPolicy", "EditRoleAssignmentPolicy")]
[assembly: WebResource("EditRoleGroup.js", "text/javascript")]
[assembly: ScriptResource("EditRoleGroup.js", "Microsoft.Exchange.Management.ControlPanel.EditRoleGroup", "EditRoleGroup")]
[assembly: WebResource("EditRoomMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditRoomMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditRoomMailbox", "EditRoomMailbox")]
[assembly: WebResource("EditTeamMailboxFVA.js", "text/javascript")]
[assembly: ScriptResource("EditTeamMailboxFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditTeamMailboxFVA", "EditTeamMailboxFVA")]
[assembly: WebResource("EditServerFVA.js", "text/javascript")]
[assembly: ScriptResource("EditServerFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditServerFVA", "EditServerFVA")]
[assembly: WebResource("IPAddressEditorFVA.js", "text/javascript")]
[assembly: ScriptResource("IPAddressEditorFVA.js", "Microsoft.Exchange.Management.ControlPanel.IPAddressEditorFVA", "IPAddressEditorFVA")]
[assembly: WebResource("SimpleIpEditorFVA.js", "text/javascript")]
[assembly: ScriptResource("SimpleIpEditorFVA.js", "Microsoft.Exchange.Management.ControlPanel.SimpleIpEditorFVA", "SimpleIpEditorFVA")]
[assembly: WebResource("EditSharingPolicyFVA.js", "text/javascript")]
[assembly: ScriptResource("EditSharingPolicyFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditSharingPolicyFVA", "EditSharingPolicyFVA")]
[assembly: WebResource("EditTransportGlobalSettingsFVA.js", "text/javascript")]
[assembly: ScriptResource("EditTransportGlobalSettingsFVA.js", "Microsoft.Exchange.Management.ControlPanel.EditTransportGlobalSettingsFVA", "EditTransportGlobalSettingsFVA")]
[assembly: WebResource("EditUMAutoAttendant.js", "text/javascript")]
[assembly: ScriptResource("EditUMAutoAttendant.js", "Microsoft.Exchange.Management.ControlPanel.EditUMAutoAttendant", "EditUMAutoAttendant")]
[assembly: WebResource("EditUMDialPlan.js", "text/javascript")]
[assembly: ScriptResource("EditUMDialPlan.js", "Microsoft.Exchange.Management.ControlPanel.EditUMDialPlan", "EditUMDialPlan")]
[assembly: WebResource("EditUMIPGateway.js", "text/javascript")]
[assembly: ScriptResource("EditUMIPGateway.js", "Microsoft.Exchange.Management.ControlPanel.EditUMIPGateway", "EditUMIPGateway")]
[assembly: WebResource("EditUMMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditUMMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditUMMailbox", "EditUMMailbox")]
[assembly: WebResource("EditUMMailboxPolicy.js", "text/javascript")]
[assembly: ScriptResource("EditUMMailboxPolicy.js", "Microsoft.Exchange.Management.ControlPanel.EditUMMailboxPolicy", "EditUMMailboxPolicy")]
[assembly: WebResource("EditWLCDMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditWLCDMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditWLCDMailbox", "EditWLCDMailbox")]
[assembly: WebResource("EditVirtualDirectory.js", "text/javascript")]
[assembly: ScriptResource("EditVirtualDirectory.js", "Microsoft.Exchange.Management.ControlPanel.EditVirtualDirectory", "EditVirtualDirectory")]
[assembly: WebResource("EnableArchiveMailbox.js", "text/javascript")]
[assembly: ScriptResource("EnableArchiveMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EnableArchiveMailbox", "EnableArchiveMailbox")]
[assembly: WebResource("EnableDisableRMSEncryptionFVA.js", "text/javascript")]
[assembly: ScriptResource("EnableDisableRMSEncryptionFVA.js", "Microsoft.Exchange.Management.ControlPanel.EnableDisableRMSEncryptionFVA", "EnableDisableRMSEncryptionFVA")]
[assembly: WebResource("EnableUMMailbox.js", "text/javascript")]
[assembly: ScriptResource("EnableUMMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EnableUMMailbox", "EnableUMMailbox")]
[assembly: WebResource("HybridConfigurationWizardFVA.js", "text/javascript")]
[assembly: ScriptResource("HybridConfigurationWizardFVA.js", "Microsoft.Exchange.Management.ControlPanel.HybridConfigurationWizardFVA", "HybridConfigurationWizardFVA")]
[assembly: WebResource("InstallExtensionFromFileFVA.js", "text/javascript")]
[assembly: ScriptResource("InstallExtensionFromFileFVA.js", "Microsoft.Exchange.Management.ControlPanel.InstallExtensionFromFileFVA", "InstallExtensionFromFileFVA")]
[assembly: WebResource("InstallExtensionFromPrivateUrlFVA.js", "text/javascript")]
[assembly: ScriptResource("InstallExtensionFromPrivateUrlFVA.js", "Microsoft.Exchange.Management.ControlPanel.InstallExtensionFromPrivateUrlFVA", "InstallExtensionFromPrivateUrlFVA")]
[assembly: WebResource("InstallMyExtensionFromFileFVA.js", "text/javascript")]
[assembly: ScriptResource("InstallMyExtensionFromFileFVA.js", "Microsoft.Exchange.Management.ControlPanel.InstallMyExtensionFromFileFVA", "InstallMyExtensionFromFileFVA")]
[assembly: WebResource("InstallMyExtensionFromPrivateUrlFVA.js", "text/javascript")]
[assembly: ScriptResource("InstallMyExtensionFromPrivateUrlFVA.js", "Microsoft.Exchange.Management.ControlPanel.InstallMyExtensionFromPrivateUrlFVA", "InstallMyExtensionFromPrivateUrlFVA")]
[assembly: WebResource("IPAddressEntryFVA.js", "text/javascript")]
[assembly: ScriptResource("IPAddressEntryFVA.js", "Microsoft.Exchange.Management.ControlPanel.IPAddressEntryFVA", "IPAddressEntryFVA")]
[assembly: WebResource("IpSafeListing.js", "text/javascript")]
[assembly: ScriptResource("IpSafeListing.js", "Microsoft.Exchange.Management.ControlPanel.IpSafeListing", "IpSafeListing")]
[assembly: WebResource("LauncherUMDialPlan.js", "text/javascript")]
[assembly: ScriptResource("LauncherUMDialPlan.js", "Microsoft.Exchange.Management.ControlPanel.LauncherUMDialPlan", "LauncherUMDialPlan")]
[assembly: WebResource("ManagePolicyFromISVFVA.js", "text/javascript")]
[assembly: ScriptResource("ManagePolicyFromISVFVA.js", "Microsoft.Exchange.Management.ControlPanel.ManagePolicyFromISVFVA", "ManagePolicyFromISVFVA")]
[assembly: WebResource("NewAcceptedDomain.js", "text/javascript")]
[assembly: ScriptResource("NewAcceptedDomain.js", "Microsoft.Exchange.Management.ControlPanel.NewAcceptedDomain", "NewAcceptedDomain")]
[assembly: WebResource("NewAddressListFVA.js", "text/javascript")]
[assembly: ScriptResource("NewAddressListFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewAddressListFVA", "NewAddressListFVA")]
[assembly: WebResource("NewAntimalwarePolicyFVA.js", "text/javascript")]
[assembly: ScriptResource("NewAntimalwarePolicyFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewAntimalwarePolicyFVA", "NewAntimalwarePolicyFVA")]
[assembly: WebResource("NewAntispamPolicyFVA.js", "text/javascript")]
[assembly: ScriptResource("NewAntispamPolicyFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewAntispamPolicyFVA", "NewAntispamPolicyFVA")]
[assembly: WebResource("NewDataClassificationFVA.js", "text/javascript")]
[assembly: ScriptResource("NewDataClassificationFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewDataClassificationFVA", "NewDataClassificationFVA")]
[assembly: WebResource("NewDeviceAccessRule.js", "text/javascript")]
[assembly: ScriptResource("NewDeviceAccessRule.js", "Microsoft.Exchange.Management.ControlPanel.NewDeviceAccessRule", "NewDeviceAccessRule")]
[assembly: WebResource("NewDiscoveryHold.js", "text/javascript")]
[assembly: ScriptResource("NewDiscoveryHold.js", "Microsoft.Exchange.Management.ControlPanel.NewDiscoveryHold", "NewDiscoveryHold")]
[assembly: WebResource("NewDistributionGroup.js", "text/javascript")]
[assembly: ScriptResource("NewDistributionGroup.js", "Microsoft.Exchange.Management.ControlPanel.NewDistributionGroup", "NewDistributionGroup")]
[assembly: WebResource("NewMyDistributionGroup.js", "text/javascript")]
[assembly: ScriptResource("NewMyDistributionGroup.js", "Microsoft.Exchange.Management.ControlPanel.NewMyDistributionGroup", "NewMyDistributionGroup")]
[assembly: WebResource("NewDataClassificationLanguageFVA.js", "text/javascript")]
[assembly: ScriptResource("NewDataClassificationLanguageFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewDataClassificationLanguageFVA", "NewDataClassificationLanguageFVA")]
[assembly: WebResource("NewDLPPolicyCustomFVA.js", "text/javascript")]
[assembly: ScriptResource("NewDLPPolicyCustomFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewDLPPolicyCustomFVA", "NewDLPPolicyCustomFVA")]
[assembly: WebResource("NewDLPPolicyFromTemplateFVA.js", "text/javascript")]
[assembly: ScriptResource("NewDLPPolicyFromTemplateFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewDLPPolicyFromTemplateFVA", "NewDLPPolicyFromTemplateFVA")]
[assembly: WebResource("NewEmailAddress.js", "text/javascript")]
[assembly: ScriptResource("NewEmailAddress.js", "Microsoft.Exchange.Management.ControlPanel.NewEmailAddress", "NewEmailAddress")]
[assembly: WebResource("NewEmailAddressPolicyFVA.js", "text/javascript")]
[assembly: ScriptResource("NewEmailAddressPolicyFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewEmailAddressPolicyFVA", "NewEmailAddressPolicyFVA")]
[assembly: WebResource("NewEquipmentMailbox.js", "text/javascript")]
[assembly: ScriptResource("NewEquipmentMailbox.js", "Microsoft.Exchange.Management.ControlPanel.NewEquipmentMailbox", "NewEquipmentMailbox")]
[assembly: WebResource("NewFFODistributionGroupFVA.js", "text/javascript")]
[assembly: ScriptResource("NewFFODistributionGroupFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewFFODistributionGroupFVA", "NewFFODistributionGroupFVA")]
[assembly: WebResource("NewFFOMailUserFVA.js", "text/javascript")]
[assembly: ScriptResource("NewFFOMailUserFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewFFOMailUserFVA", "NewFFOMailUserFVA")]
[assembly: WebResource("NewImapSubscription.js", "text/javascript")]
[assembly: ScriptResource("NewImapSubscription.js", "Microsoft.Exchange.Management.ControlPanel.NewImapSubscription", "NewImapSubscription")]
[assembly: WebResource("NewInboundConnectorFVA.js", "text/javascript")]
[assembly: ScriptResource("NewInboundConnectorFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewInboundConnectorFVA", "NewInboundConnectorFVA")]
[assembly: WebResource("NewOutboundConnectorFVA.js", "text/javascript")]
[assembly: ScriptResource("NewOutboundConnectorFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewOutboundConnectorFVA", "NewOutboundConnectorFVA")]
[assembly: WebResource("NewLinkedMailboxFVA.js", "text/javascript")]
[assembly: ScriptResource("NewLinkedMailboxFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewLinkedMailboxFVA", "NewLinkedMailboxFVA")]
[assembly: WebResource("NewMailbox.js", "text/javascript")]
[assembly: ScriptResource("NewMailbox.js", "Microsoft.Exchange.Management.ControlPanel.NewMailbox", "NewMailbox")]
[assembly: WebResource("NewMailboxExportRequest.js", "text/javascript")]
[assembly: ScriptResource("NewMailboxExportRequest.js", "Microsoft.Exchange.Management.ControlPanel.NewMailboxExportRequest", "NewMailboxExportRequest")]
[assembly: WebResource("NewMailboxImportRequest.js", "text/javascript")]
[assembly: ScriptResource("NewMailboxImportRequest.js", "Microsoft.Exchange.Management.ControlPanel.NewMailboxImportRequest", "NewMailboxImportRequest")]
[assembly: WebResource("NewMailboxSearch.js", "text/javascript")]
[assembly: ScriptResource("NewMailboxSearch.js", "Microsoft.Exchange.Management.ControlPanel.NewMailboxSearch", "NewMailboxSearch")]
[assembly: WebResource("NewMailContact.js", "text/javascript")]
[assembly: ScriptResource("NewMailContact.js", "Microsoft.Exchange.Management.ControlPanel.NewMailContact", "NewMailContact")]
[assembly: WebResource("NewMailUser.js", "text/javascript")]
[assembly: ScriptResource("NewMailUser.js", "Microsoft.Exchange.Management.ControlPanel.NewMailUser", "NewMailUser")]
[assembly: WebResource("NewMigrationBatch.js", "text/javascript")]
[assembly: ScriptResource("NewMigrationBatch.js", "Microsoft.Exchange.Management.ControlPanel.NewMigrationBatch", "NewMigrationBatch")]
[assembly: WebResource("NewMigrationEndpoint.js", "text/javascript")]
[assembly: ScriptResource("NewMigrationEndpoint.js", "Microsoft.Exchange.Management.ControlPanel.NewMigrationEndpoint", "NewMigrationEndpoint")]
[assembly: WebResource("NewOrganizationRelationshipFVA.js", "text/javascript")]
[assembly: ScriptResource("NewOrganizationRelationshipFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewOrganizationRelationshipFVA", "NewOrganizationRelationshipFVA")]
[assembly: WebResource("NewPopSubscription.js", "text/javascript")]
[assembly: ScriptResource("NewPopSubscription.js", "Microsoft.Exchange.Management.ControlPanel.NewPopSubscription", "NewPopSubscription")]
[assembly: WebResource("NewRemoteMailbox.js", "text/javascript")]
[assembly: ScriptResource("NewRemoteMailbox.js", "Microsoft.Exchange.Management.ControlPanel.NewRemoteMailbox", "NewRemoteMailbox")]
[assembly: WebResource("NewRemoteDomain.js", "text/javascript")]
[assembly: ScriptResource("NewRemoteDomain.js", "Microsoft.Exchange.Management.ControlPanel.NewRemoteDomain", "NewRemoteDomain")]
[assembly: WebResource("NewSharedMailbox.js", "text/javascript")]
[assembly: ScriptResource("NewSharedMailbox.js", "Microsoft.Exchange.Management.ControlPanel.NewSharedMailbox", "NewSharedMailbox")]
[assembly: WebResource("EditSharedMailbox.js", "text/javascript")]
[assembly: ScriptResource("EditSharedMailbox.js", "Microsoft.Exchange.Management.ControlPanel.EditSharedMailbox", "EditSharedMailbox")]
[assembly: WebResource("NewRoleAssignmentPolicy.js", "text/javascript")]
[assembly: ScriptResource("NewRoleAssignmentPolicy.js", "Microsoft.Exchange.Management.ControlPanel.NewRoleAssignmentPolicy", "NewRoleAssignmentPolicy")]
[assembly: WebResource("NewRoomMailbox.js", "text/javascript")]
[assembly: ScriptResource("NewRoomMailbox.js", "Microsoft.Exchange.Management.ControlPanel.NewRoomMailbox", "NewRoomMailbox")]
[assembly: WebResource("NewSharingPolicyFVA.js", "text/javascript")]
[assembly: ScriptResource("NewSharingPolicyFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewSharingPolicyFVA", "NewSharingPolicyFVA")]
[assembly: WebResource("NewSubscription.js", "text/javascript")]
[assembly: ScriptResource("NewSubscription.js", "Microsoft.Exchange.Management.ControlPanel.NewSubscription", "NewSubscription")]
[assembly: WebResource("NewUMAutoAttendant.js", "text/javascript")]
[assembly: ScriptResource("NewUMAutoAttendant.js", "Microsoft.Exchange.Management.ControlPanel.NewUMAutoAttendant", "NewUMAutoAttendant")]
[assembly: WebResource("NewUMDialPlan.js", "text/javascript")]
[assembly: ScriptResource("NewUMDialPlan.js", "Microsoft.Exchange.Management.ControlPanel.NewUMDialPlan", "NewUMDialPlan")]
[assembly: WebResource("NewUMHuntGroup.js", "text/javascript")]
[assembly: ScriptResource("NewUMHuntGroup.js", "Microsoft.Exchange.Management.ControlPanel.NewUMHuntGroup", "NewUMHuntGroup")]
[assembly: WebResource("NewUMIPGateway.js", "text/javascript")]
[assembly: ScriptResource("NewUMIPGateway.js", "Microsoft.Exchange.Management.ControlPanel.NewUMIPGateway", "NewUMIPGateway")]
[assembly: WebResource("NewUMMailboxPolicy.js", "text/javascript")]
[assembly: ScriptResource("NewUMMailboxPolicy.js", "Microsoft.Exchange.Management.ControlPanel.NewUMMailboxPolicy", "NewUMMailboxPolicy")]
[assembly: WebResource("NewOutlookSettingsFVA.js", "text/javascript")]
[assembly: ScriptResource("NewOutlookSettingsFVA.js", "Microsoft.Exchange.Management.ControlPanel.NewOutlookSettingsFVA", "NewOutlookSettingsFVA")]
[assembly: WebResource("ReleaseQuarantineFVA.js", "text/javascript")]
[assembly: ScriptResource("ReleaseQuarantineFVA.js", "Microsoft.Exchange.Management.ControlPanel.ReleaseQuarantineFVA", "ReleaseQuarantineFVA")]
[assembly: WebResource("ResetPassword.js", "text/javascript")]
[assembly: ScriptResource("ResetPassword.js", "Microsoft.Exchange.Management.ControlPanel.ResetPassword", "ResetPassword")]
[assembly: WebResource("ResetUMMailboxPin.js", "text/javascript")]
[assembly: ScriptResource("ResetUMMailboxPin.js", "Microsoft.Exchange.Management.ControlPanel.ResetUMMailboxPin", "ResetUMMailboxPin")]
[assembly: WebResource("SearchDeliveryReports.js", "text/javascript")]
[assembly: ScriptResource("SearchDeliveryReports.js", "Microsoft.Exchange.Management.ControlPanel.SearchDeliveryReports", "SearchDeliveryReports")]
[assembly: WebResource("ServerSwitchoverFVA.js", "text/javascript")]
[assembly: ScriptResource("ServerSwitchoverFVA.js", "Microsoft.Exchange.Management.ControlPanel.ServerSwitchoverFVA", "ServerSwitchoverFVA")]
[assembly: WebResource("MessageTraceFVA.js", "text/javascript")]
[assembly: ScriptResource("MessageTraceFVA.js", "Microsoft.Exchange.Management.ControlPanel.MessageTraceFVA", "MessageTraceFVA")]
[assembly: WebResource("MessageTraceExFVA.js", "text/javascript")]
[assembly: ScriptResource("MessageTraceExFVA.js", "Microsoft.Exchange.Management.ControlPanel.MessageTraceExFVA", "MessageTraceExFVA")]
[assembly: WebResource("SharingRuleEntryFVA.js", "text/javascript")]
[assembly: ScriptResource("SharingRuleEntryFVA.js", "Microsoft.Exchange.Management.ControlPanel.SharingRuleEntryFVA", "SharingRuleEntryFVA")]
[assembly: WebResource("UpdateDatabaseCopyFVA.js", "text/javascript")]
[assembly: ScriptResource("UpdateDatabaseCopyFVA.js", "Microsoft.Exchange.Management.ControlPanel.UpdateDatabaseCopyFVA", "UpdateDatabaseCopyFVA")]
[assembly: WebResource("UMCallSummaryReportFVA.js", "text/javascript")]
[assembly: ScriptResource("UMCallSummaryReportFVA.js", "Microsoft.Exchange.Management.ControlPanel.UMCallSummaryReportFVA", "UMCallSummaryReportFVA")]
[assembly: WebResource("UMDialingRuleEntry.js", "text/javascript")]
[assembly: ScriptResource("UMDialingRuleEntry.js", "Microsoft.Exchange.Management.ControlPanel.UMDialingRuleEntry", "UMDialingRuleEntry")]
[assembly: WebResource("UMHolidayScheduleForm.js", "text/javascript")]
[assembly: ScriptResource("UMHolidayScheduleForm.js", "Microsoft.Exchange.Management.ControlPanel.UMHolidayScheduleForm", "UMHolidayScheduleForm")]
[assembly: WebResource("UMKeyMappingForm.js", "text/javascript")]
[assembly: ScriptResource("UMKeyMappingForm.js", "Microsoft.Exchange.Management.ControlPanel.UMKeyMappingForm", "UMKeyMappingForm")]
[assembly: WebResource("VoicemailConfiguration.js", "text/javascript")]
[assembly: ScriptResource("VoicemailConfiguration.js", "Microsoft.Exchange.Management.ControlPanel.VoicemailConfiguration", "VoicemailConfiguration")]
[assembly: WebResource("EditPublicFolders.js", "text/javascript")]
