using System;
using System.Collections.Generic;
using Microsoft.Exchange.Data;
using Microsoft.Exchange.Data.Storage;
using Microsoft.Exchange.Diagnostics;

namespace Microsoft.Exchange.Transport.Sync.Common.ImportContacts
{
	[ClassAccessLevel(AccessLevel.MSInternal)]
	internal class ImportContactXsoMapper
	{
		internal static Dictionary<ImportContactProperties, StorePropertyDefinition> PropertiesMapping
		{
			get
			{
				return ImportContactXsoMapper.propertiesMapping;
			}
		}

		internal static StorePropertyDefinition GetProperty(ImportContactProperties property)
		{
			StorePropertyDefinition result;
			ImportContactXsoMapper.PropertiesMapping.TryGetValue(property, out result);
			return result;
		}

		internal static bool ValidatePropertyValue(ImportContactProperties property, object value)
		{
			StorePropertyDefinition property2 = ImportContactXsoMapper.GetProperty(property);
			if (property2 == null)
			{
				return true;
			}
			switch (property)
			{
			case ImportContactProperties.EmailAddress:
			case ImportContactProperties.EmailDisplayName:
			case ImportContactProperties.Email2Address:
			case ImportContactProperties.Email2DisplayName:
			case ImportContactProperties.Email3Address:
			case ImportContactProperties.Email3DisplayName:
				return true;
			case ImportContactProperties.EmailType:
			case ImportContactProperties.Email2Type:
			case ImportContactProperties.Email3Type:
			{
				string text = (string)value;
				return text.Length <= 9;
			}
			default:
			{
				PropertyValidationError[] array = property2.Validate(null, value);
				return array.Length == 0;
			}
			}
		}

		private static Dictionary<ImportContactProperties, StorePropertyDefinition> propertiesMapping = new Dictionary<ImportContactProperties, StorePropertyDefinition>
		{
			{
				ImportContactProperties.IgnoredProperty,
				null
			},
			{
				ImportContactProperties.Title,
				ContactSchema.DisplayNamePrefix
			},
			{
				ImportContactProperties.FirstName,
				ContactSchema.GivenName
			},
			{
				ImportContactProperties.MiddleName,
				ContactSchema.MiddleName
			},
			{
				ImportContactProperties.LastName,
				ContactSchema.Surname
			},
			{
				ImportContactProperties.Suffix,
				ContactSchema.Generation
			},
			{
				ImportContactProperties.JobTitle,
				ContactSchema.Title
			},
			{
				ImportContactProperties.Nickname,
				ContactSchema.Nickname
			},
			{
				ImportContactProperties.Company,
				ContactSchema.CompanyName
			},
			{
				ImportContactProperties.Department,
				ContactSchema.Department
			},
			{
				ImportContactProperties.BusinessStreet,
				ContactSchema.WorkAddressStreet
			},
			{
				ImportContactProperties.BusinessStreet2,
				ContactSchema.WorkAddressStreet
			},
			{
				ImportContactProperties.BusinessStreet3,
				ContactSchema.WorkAddressStreet
			},
			{
				ImportContactProperties.BusinessCity,
				ContactSchema.WorkAddressCity
			},
			{
				ImportContactProperties.BusinessState,
				ContactSchema.WorkAddressState
			},
			{
				ImportContactProperties.BusinessPostalCode,
				ContactSchema.WorkAddressPostalCode
			},
			{
				ImportContactProperties.BusinessCountryOrRegion,
				ContactSchema.WorkAddressCountry
			},
			{
				ImportContactProperties.HomeStreet,
				ContactSchema.HomeStreet
			},
			{
				ImportContactProperties.HomeStreet2,
				ContactSchema.HomeStreet
			},
			{
				ImportContactProperties.HomeStreet3,
				ContactSchema.HomeStreet
			},
			{
				ImportContactProperties.HomeCity,
				ContactSchema.HomeCity
			},
			{
				ImportContactProperties.HomeState,
				ContactSchema.HomeState
			},
			{
				ImportContactProperties.HomePostalCode,
				ContactSchema.HomePostalCode
			},
			{
				ImportContactProperties.HomeCountryOrRegion,
				ContactSchema.HomeCountry
			},
			{
				ImportContactProperties.OtherStreet,
				ContactSchema.OtherStreet
			},
			{
				ImportContactProperties.OtherStreet2,
				ContactSchema.OtherStreet
			},
			{
				ImportContactProperties.OtherStreet3,
				ContactSchema.OtherStreet
			},
			{
				ImportContactProperties.OtherCity,
				ContactSchema.OtherCity
			},
			{
				ImportContactProperties.OtherState,
				ContactSchema.OtherState
			},
			{
				ImportContactProperties.OtherPostalCode,
				ContactSchema.OtherPostalCode
			},
			{
				ImportContactProperties.OtherCountryOrRegion,
				ContactSchema.OtherCountry
			},
			{
				ImportContactProperties.AssistantPhone,
				ContactSchema.AssistantPhoneNumber
			},
			{
				ImportContactProperties.BusinessFax,
				ContactSchema.WorkFax
			},
			{
				ImportContactProperties.BusinessPhone,
				ContactSchema.BusinessPhoneNumber
			},
			{
				ImportContactProperties.BusinessPhone2,
				ContactSchema.BusinessPhoneNumber2
			},
			{
				ImportContactProperties.Callback,
				ContactSchema.CallbackPhone
			},
			{
				ImportContactProperties.CarPhone,
				ContactSchema.CarPhone
			},
			{
				ImportContactProperties.CompanyMainPhone,
				ContactSchema.OrganizationMainPhone
			},
			{
				ImportContactProperties.HomeFax,
				ContactSchema.HomeFax
			},
			{
				ImportContactProperties.HomePhone,
				ContactSchema.HomePhone
			},
			{
				ImportContactProperties.HomePhone2,
				ContactSchema.HomePhone2
			},
			{
				ImportContactProperties.ISDN,
				ContactSchema.InternationalIsdnNumber
			},
			{
				ImportContactProperties.MobilePhone,
				ContactSchema.MobilePhone
			},
			{
				ImportContactProperties.OtherFax,
				ContactSchema.OtherFax
			},
			{
				ImportContactProperties.OtherPhone,
				ContactSchema.OtherTelephone
			},
			{
				ImportContactProperties.Pager,
				ContactSchema.Pager
			},
			{
				ImportContactProperties.PrimaryPhone,
				ContactSchema.PrimaryTelephoneNumber
			},
			{
				ImportContactProperties.RadioPhone,
				ContactSchema.RadioPhone
			},
			{
				ImportContactProperties.TTYOrTDDPhone,
				ContactSchema.TtyTddPhoneNumber
			},
			{
				ImportContactProperties.Telex,
				ContactSchema.TelexNumber
			},
			{
				ImportContactProperties.Anniversary,
				ContactSchema.WeddingAnniversaryLocal
			},
			{
				ImportContactProperties.AssistantName,
				ContactSchema.AssistantName
			},
			{
				ImportContactProperties.Birthday,
				ContactSchema.BirthdayLocal
			},
			{
				ImportContactProperties.BusinessPOBox,
				ContactSchema.WorkPostOfficeBox
			},
			{
				ImportContactProperties.Categories,
				ItemSchema.Categories
			},
			{
				ImportContactProperties.Children,
				ContactSchema.Children
			},
			{
				ImportContactProperties.EmailAddress,
				ContactSchema.Email1
			},
			{
				ImportContactProperties.EmailType,
				ContactSchema.Email1
			},
			{
				ImportContactProperties.EmailDisplayName,
				ContactSchema.Email1
			},
			{
				ImportContactProperties.Email2Address,
				ContactSchema.Email2
			},
			{
				ImportContactProperties.Email2Type,
				ContactSchema.Email2
			},
			{
				ImportContactProperties.Email2DisplayName,
				ContactSchema.Email2
			},
			{
				ImportContactProperties.Email3Address,
				ContactSchema.Email3
			},
			{
				ImportContactProperties.Email3Type,
				ContactSchema.Email3
			},
			{
				ImportContactProperties.Email3DisplayName,
				ContactSchema.Email3
			},
			{
				ImportContactProperties.GovernmentIDNumber,
				ContactSchema.GovernmentIdNumber
			},
			{
				ImportContactProperties.Hobby,
				ContactSchema.Hobbies
			},
			{
				ImportContactProperties.HomePOBox,
				ContactSchema.HomePostOfficeBox
			},
			{
				ImportContactProperties.Initials,
				ContactSchema.Initials
			},
			{
				ImportContactProperties.InternetFreeBusy,
				ContactSchema.FreeBusyUrl
			},
			{
				ImportContactProperties.ManagerName,
				ContactSchema.Manager
			},
			{
				ImportContactProperties.Mileage,
				ContactSchema.Mileage
			},
			{
				ImportContactProperties.Notes,
				null
			},
			{
				ImportContactProperties.OfficeLocation,
				ContactSchema.OfficeLocation
			},
			{
				ImportContactProperties.OtherPOBox,
				ContactSchema.OtherPostOfficeBox
			},
			{
				ImportContactProperties.Profession,
				ContactSchema.Profession
			},
			{
				ImportContactProperties.Spouse,
				ContactSchema.SpouseName
			},
			{
				ImportContactProperties.User1,
				ContactSchema.UserText1
			},
			{
				ImportContactProperties.User2,
				ContactSchema.UserText2
			},
			{
				ImportContactProperties.User3,
				ContactSchema.UserText3
			},
			{
				ImportContactProperties.User4,
				ContactSchema.UserText4
			},
			{
				ImportContactProperties.WebPage,
				ContactSchema.BusinessHomePage
			},
			{
				ImportContactProperties.CompanyYomi,
				ContactSchema.YomiCompany
			},
			{
				ImportContactProperties.GivenYomi,
				ContactSchema.YomiFirstName
			},
			{
				ImportContactProperties.SurnameYomi,
				ContactSchema.YomiLastName
			},
			{
				ImportContactProperties.Account,
				ContactSchema.Account
			},
			{
				ImportContactProperties.BillingInformation,
				ContactSchema.BillingInformation
			},
			{
				ImportContactProperties.Location,
				ContactSchema.Location
			},
			{
				ImportContactProperties.Gender,
				null
			},
			{
				ImportContactProperties.Priority,
				null
			},
			{
				ImportContactProperties.Sensitivity,
				null
			},
			{
				ImportContactProperties.IMAddress,
				ContactSchema.IMAddress
			},
			{
				ImportContactProperties.Schools,
				ContactSchema.Schools
			},
			{
				ImportContactProperties.PersonalWebPage,
				ContactSchema.PersonalHomePage
			},
			{
				ImportContactProperties.MobilePhone2,
				ContactSchema.CarPhone
			}
		};
	}
}
