using System;

namespace Microsoft.Mapi
{
	internal enum MapiClientType
	{
		System = 1,
		Administrator,
		User,
		Transport,
		AirSync,
		EventBasedAssistants,
		OWA,
		PopImap,
		RpcHttp,
		ContentIndexing,
		AvailabilityService,
		ELC,
		Management,
		Monitoring,
		UnifiedMessaging,
		WebServices,
		ApprovalAPI,
		TimeBasedAssistants,
		MoMT,
		Migration,
		TransportSync,
		HA,
		Maintenance,
		Inference,
		SMS,
		TeamMailbox,
		StoreActiveMonitoring,
		LoadGen,
		SimpleMigration,
		PublicFolderSystem,
		EDiscoverySearch,
		ContentIndexingMoveDestination,
		AnchorService,
		MailboxLoadBalance,
		OutlookService,
		UnifiedPolicy,
		NotificationBroker,
		Pop,
		LiveIdBasicAuth,
		ADDriver,
		SnackyService,
		MaxValue
	}
}
