using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Runtime.Serialization;

namespace Microsoft.Online.Administration.WebService
{
	[KnownType(typeof(ContactNotFoundException))]
	[KnownType(typeof(DomainUnexpectedAuthenticationException))]
	[KnownType(typeof(DomainCapabilitySetException))]
	[KnownType(typeof(DomainLiveNamespaceExistsException))]
	[KnownType(typeof(DomainNotRootException))]
	[KnownType(typeof(DomainLiveNamespaceAuthenticationException))]
	[KnownType(typeof(DomainLiveNamespaceUriConflictException))]
	[KnownType(typeof(DomainNameForbiddenWordException))]
	[KnownType(typeof(DomainPendingDeletionException))]
	[KnownType(typeof(DomainVerificationMissingCnameException))]
	[KnownType(typeof(DomainVerificationWrongCnameTargetException))]
	[KnownType(typeof(DomainVerificationMissingDnsRecordException))]
	[KnownType(typeof(DomainLiveNamespaceUnmanagedException))]
	[KnownType(typeof(DomainCapabilityUnsetException))]
	[KnownType(typeof(DefaultDomainDeletionException))]
	[KnownType(typeof(InitialDomainDeletionException))]
	[KnownType(typeof(DomainHasChildDomainException))]
	[KnownType(typeof(DomainNotEmptyException))]
	[KnownType(typeof(SetUnverifiedDomainAsDefaultException))]
	[KnownType(typeof(DefaultDomainUnsetException))]
	[KnownType(typeof(DefaultDomainInvalidAuthenticationException))]
	[KnownType(typeof(InitialDomainUpdateException))]
	[KnownType(typeof(DomainCapabilityUnavailableException))]
	[KnownType(typeof(DomainOverlappingOperationException))]
	[GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
	[DataContract(Name = "DataOperationException", Namespace = "http://schemas.datacontract.org/2004/07/Microsoft.Online.Administration.WebService")]
	[KnownType(typeof(ObjectNotFoundException))]
	[KnownType(typeof(InvalidContextException))]
	[KnownType(typeof(ServicePrincipalNotFoundException))]
	[KnownType(typeof(UserNotFoundException))]
	[KnownType(typeof(CompanyNotFoundException))]
	[KnownType(typeof(RoleNotFoundException))]
	[KnownType(typeof(RoleMemberNotFoundException))]
	[KnownType(typeof(SubscriptionNotFoundException))]
	[KnownType(typeof(DomainNotFoundException))]
	[KnownType(typeof(ContractNotFoundException))]
	[DebuggerStepThrough]
	[KnownType(typeof(GroupNotFoundException))]
	[KnownType(typeof(GroupMemberNotFoundException))]
	[KnownType(typeof(PageNotAvailableException))]
	[KnownType(typeof(InvalidListContextException))]
	[KnownType(typeof(ObjectAlreadyExistsException))]
	[KnownType(typeof(MemberAlreadyExistsException))]
	[KnownType(typeof(UserAlreadyExistsException))]
	[KnownType(typeof(DomainAlreadyExistsException))]
	[KnownType(typeof(DomainAlreadyExistsInOldSystemException))]
	[KnownType(typeof(DomainNameConflictException))]
	[KnownType(typeof(GroupAlreadyExistsException))]
	[KnownType(typeof(RemoveSelfFromRoleException))]
	[KnownType(typeof(RemoveDirSyncObjectNotAllowedException))]
	[KnownType(typeof(UserRemoveSelfException))]
	[KnownType(typeof(UserConflictAuthenticationException))]
	[KnownType(typeof(RestoreUserLicenseErrorException))]
	[KnownType(typeof(RestoreUserErrorException))]
	[KnownType(typeof(RestoreUserNotAllowedException))]
	[KnownType(typeof(DirSyncStatusChangeNotAllowedException))]
	[KnownType(typeof(DomainDataOperationException))]
	public class DataOperationException : MsolAdministrationException
	{
	}
}
