using System;

namespace Microsoft.Exchange.Protocols.MAPI
{
	[Flags]
	public enum RopFlags
	{
		Private = 1,
		Undercover = 2,
		Ghosted = 4,
		SplProcess = 8,
		Mapi0 = 16,
		MbxGuids = 32,
		Extended = 64,
		NoRulesInterface = 128,
		ReadOnly = 0,
		ReadWrite = 1,
		Create = 2,
		BestAccess = 3,
		OpenSoftDeleted = 4,
		NoBlock = 8,
		Append = 4,
		Wait = 0,
		NoWait = 1,
		Advance = 0,
		NoAdvance = 1,
		SendMax = 2,
		Close = 0,
		KeepOpenReadOnly = 1,
		KeepOpenReadWrite = 2,
		ForceSave = 4,
		DelayedCall = 8,
		ICS = 512,
		ExtendedReg = 4,
		ReplaceAll = 1,
		Categorize = 1,
		Associated = 2,
		Depth = 4,
		DeferredErrors = 8,
		NoNotifs = 16,
		SoftDeletes = 32,
		MapiUnicode = 64,
		IgnoreMe = 128,
		MarkRead = 1,
		SendRN = 2,
		Preprocess = 1,
		SystemSubmit = 16,
		NeedsSpooler = 8192,
		IgnoreSendAsRight = 131072,
		GenByRule = 16384,
		DelegateSend = 32768,
		delMessages = 1,
		delFolders = 4,
		delAssociated = 8,
		delHardDelete = 16,
		delAssoc = 1,
		delForce = 2,
		clientAssociatedFlag = 64,
		contentAggregation = 1
	}
}
