using System;

namespace Microsoft.Exchange.Cluster.ClusApi
{
	internal enum AmClusterNetworkControlCode : uint
	{
		CLUSCTL_NETWORK_GET_RO_COMMON_PROPERTIES = 83886165U,
		CLUSCTL_NETWORK_GET_COMMON_PROPERTIES = 83886169U,
		CLUSCTL_NETWORK_SET_COMMON_PROPERTIES = 88080478U,
		CLUSCTL_NETWORK_GET_PRIVATE_PROPERTIES = 83886209U,
		CLUSCTL_NETWORK_SET_PRIVATE_PROPERTIES = 88080518U
	}
}
