using System;
using System.Runtime.InteropServices;

namespace System.Globalization
{
	[ComVisible(true)]
	[__DynamicallyInvokable]
	[Serializable]
	public enum UnicodeCategory
	{
		[__DynamicallyInvokable]
		UppercaseLetter,
		[__DynamicallyInvokable]
		LowercaseLetter,
		[__DynamicallyInvokable]
		TitlecaseLetter,
		[__DynamicallyInvokable]
		ModifierLetter,
		[__DynamicallyInvokable]
		OtherLetter,
		[__DynamicallyInvokable]
		NonSpacingMark,
		[__DynamicallyInvokable]
		SpacingCombiningMark,
		[__DynamicallyInvokable]
		EnclosingMark,
		[__DynamicallyInvokable]
		DecimalDigitNumber,
		[__DynamicallyInvokable]
		LetterNumber,
		[__DynamicallyInvokable]
		OtherNumber,
		[__DynamicallyInvokable]
		SpaceSeparator,
		[__DynamicallyInvokable]
		LineSeparator,
		[__DynamicallyInvokable]
		ParagraphSeparator,
		[__DynamicallyInvokable]
		Control,
		[__DynamicallyInvokable]
		Format,
		[__DynamicallyInvokable]
		Surrogate,
		[__DynamicallyInvokable]
		PrivateUse,
		[__DynamicallyInvokable]
		ConnectorPunctuation,
		[__DynamicallyInvokable]
		DashPunctuation,
		[__DynamicallyInvokable]
		OpenPunctuation,
		[__DynamicallyInvokable]
		ClosePunctuation,
		[__DynamicallyInvokable]
		InitialQuotePunctuation,
		[__DynamicallyInvokable]
		FinalQuotePunctuation,
		[__DynamicallyInvokable]
		OtherPunctuation,
		[__DynamicallyInvokable]
		MathSymbol,
		[__DynamicallyInvokable]
		CurrencySymbol,
		[__DynamicallyInvokable]
		ModifierSymbol,
		[__DynamicallyInvokable]
		OtherSymbol,
		[__DynamicallyInvokable]
		OtherNotAssigned
	}
}
