using System;

namespace Microsoft.Exchange.BITS
{
	[Flags]
	internal enum BG_HTTP_OPTIONS_SECURITY_FLAGS : ulong
	{
		BG_SSL_ENABLE_CRL_CHECK = 1UL,
		BG_SSL_IGNORE_CERT_CN_INVALID = 2UL,
		BG_SSL_IGNORE_CERT_DATE_INVALID = 4UL,
		BG_SSL_IGNORE_UNKNOWN_CA = 8UL,
		BG_SSL_IGNORE_CERT_WRONG_USAGE = 16UL,
		BG_HTTP_REDIRECT_POLICY_ALLOW_SILENT = 0UL,
		BG_HTTP_REDIRECT_POLICY_ALLOW_REPORT = 256UL,
		BG_HTTP_REDIRECT_POLICY_DISALLOW = 512UL,
		BG_HTTP_REDIRECT_POLICY_MASK = 1792UL,
		BG_HTTP_REDIRECT_POLICY_ALLOW_HTTPS_TO_HTTP = 2048UL
	}
}
